 var schools1 = { 
    "type" : "FeatureCollection",
        "features" : [
             { "type" : "Feature",
        "id" : 109,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.7269516,44.3910217]},
        		"properties" : { 
        				 "NAME" : "Andrew Hunter", 
        				 "MUNICIPALITY" : "Barrie", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "59 Lampman Lane", 
        				 "POSTALCODE" : "L4N5G4",
        				 "PHONE" : "7057285420",
        				 "FAX" : "7057282110",
        				 "WEB" : "http://anh.scdsb.on.ca",
        				 "BOARD_NAME" : "Simcoe County DSB",
        				 "ProvincalName" : "Andrew Hunter,Barrie",
        				 "Rating2011_12" : "1.5", 
        				 "Rating_in_the_most_recent_five_years" : "2.7", 
        				 "Rank2011_12" : "2667/2714",
        				 "Rank_in_the_most_recent_five_years" : "2206/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 150,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.5421906,43.8352318]},
        		"properties" : { 
        				 "NAME" : "Arthur", 
        				 "MUNICIPALITY" : "Arthur", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 148", 
        				 "STREET" : "155 Conestoga St N", 
        				 "POSTALCODE" : "N0G1A0",
        				 "PHONE" : "5198483793",
        				 "FAX" : "5198485994",
        				 "WEB" : "http://www.ugdsb.on.ca/arthur/",
        				 "BOARD_NAME" : "Upper Grand DSB",
        				 "ProvincalName" : "Arthur,Arthur",
        				 "Rating2011_12" : "1.9", 
        				 "Rating_in_the_most_recent_five_years" : "4.6", 
        				 "Rank2011_12" : "2645/2714",
        				 "Rank_in_the_most_recent_five_years" : "1888/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 251,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.2504883,43.1231308]},
        		"properties" : { 
        				 "NAME" : "Bellview", 
        				 "MUNICIPALITY" : "Brantford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "97 Tenth Ave", 
        				 "POSTALCODE" : "N3S1G5",
        				 "PHONE" : "5197527414",
        				 "FAX" : "5197529818",
        				 "WEB" : "http://granderie.ca/bellview",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Bellview,Brantford",
        				 "Rating2011_12" : "1", 
        				 "Rating_in_the_most_recent_five_years" : "1", 
        				 "Rank2011_12" : "2691/2714",
        				 "Rank_in_the_most_recent_five_years" : "2265/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 324,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2182007,43.0051003]},
        		"properties" : { 
        				 "NAME" : "Blessed Sacrament", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1063 Oxford St E", 
        				 "POSTALCODE" : "N5Y3L4",
        				 "PHONE" : "5196754411",
        				 "FAX" : "",
        				 "WEB" : "www.ldcsb.on.ca/schools/sacrament",
        				 "BOARD_NAME" : "London District Board",
        				 "ProvincalName" : "Blessed Sacrament,London",
        				 "Rating2011_12" : "1.5", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2667/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 520,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.8463364,43.2572784]},
        		"properties" : { 
        				 "NAME" : "Cathy Wever", 
        				 "MUNICIPALITY" : "Hamilton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "160 Wentworth Street North", 
        				 "POSTALCODE" : "L8L5V7",
        				 "PHONE" : "9055229965",
        				 "FAX" : "",
        				 "WEB" : "www.hwdsb.on.ca/cathywever",
        				 "BOARD_NAME" : "Hamilton-Wentworth DSB",
        				 "ProvincalName" : "Cathy Wever,Hamilton",
        				 "Rating2011_12" : "1.6", 
        				 "Rating_in_the_most_recent_five_years" : "1.8", 
        				 "Rank2011_12" : "2661/2714",
        				 "Rank_in_the_most_recent_five_years" : "2246/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 527,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.841835,43.2033272]},
        		"properties" : { 
        				 "NAME" : "Cecil B Stirling", 
        				 "MUNICIPALITY" : "Hamilton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "340 Queen Victoria Drive", 
        				 "POSTALCODE" : "L8W1T9",
        				 "PHONE" : "9053855374",
        				 "FAX" : "9053850072",
        				 "WEB" : "www.hwdsb.on.ca/cecilbstirling",
        				 "BOARD_NAME" : "Hamilton-Wentworth DSB",
        				 "ProvincalName" : "Cecil B Stirling,Hamilton",
        				 "Rating2011_12" : "1.1", 
        				 "Rating_in_the_most_recent_five_years" : "2", 
        				 "Rank2011_12" : "2686/2714",
        				 "Rank_in_the_most_recent_five_years" : "2239/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 568,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-74.7254028,45.0196304]},
        		"properties" : { 
        				 "NAME" : "Central", 
        				 "MUNICIPALITY" : "Cornwall", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "200 Amelia Street", 
        				 "POSTALCODE" : "K6H0A5",
        				 "PHONE" : "6139320857",
        				 "FAX" : "6139328345",
        				 "WEB" : "http://www.ucdsb.on.ca/Schools/School+Directory/Elementary/CES/homepage.htm",
        				 "BOARD_NAME" : "Upper Canada DSB",
        				 "ProvincalName" : "Central,Cornwall",
        				 "Rating2011_12" : "1.9", 
        				 "Rating_in_the_most_recent_five_years" : "3", 
        				 "Rank2011_12" : "2645/2714",
        				 "Rank_in_the_most_recent_five_years" : "2179/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 874,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-78.8509598,43.8658714]},
        		"properties" : { 
        				 "NAME" : "Dr C F Cannon", 
        				 "MUNICIPALITY" : "Oshawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1196 Cedar St", 
        				 "POSTALCODE" : "L1J3S2",
        				 "PHONE" : "9057250344",
        				 "FAX" : "9057258233",
        				 "WEB" : "http://cannon.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "Dr C F Cannon,Oshawa",
        				 "Rating2011_12" : "2", 
        				 "Rating_in_the_most_recent_five_years" : "2.6", 
        				 "Rank2011_12" : "2639/2714",
        				 "Rank_in_the_most_recent_five_years" : "2218/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 880,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.8007126,45.3603287]},
        		"properties" : { 
        				 "NAME" : "Dr F J McDonald", 
        				 "MUNICIPALITY" : "Ottawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2860 Ahearn Ave", 
        				 "POSTALCODE" : "K2B6Z9",
        				 "PHONE" : "6138293878",
        				 "FAX" : "6138293782",
        				 "WEB" : "http://www.ottawacatholicschools.ca/dfj",
        				 "BOARD_NAME" : "Ottawa CDSB",
        				 "ProvincalName" : "Dr F J McDonald,Ottawa",
        				 "Rating2011_12" : "1.9", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2645/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 928,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2001038,42.9790993]},
        		"properties" : { 
        				 "NAME" : "Ealing", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "840 Hamilton Rd", 
        				 "POSTALCODE" : "N5Z1V5",
        				 "PHONE" : "5194528150",
        				 "FAX" : "5194528159",
        				 "WEB" : "http://www.tvdsb.ca/Ealing.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Ealing,London",
        				 "Rating2011_12" : "1.8", 
        				 "Rating_in_the_most_recent_five_years" : "2", 
        				 "Rank2011_12" : "2655/2714",
        				 "Rank_in_the_most_recent_five_years" : "2239/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1491,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.1958008,43.0233002]},
        		"properties" : { 
        				 "NAME" : "Evelyn Harrison", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "50 Tewksbury Cres", 
        				 "POSTALCODE" : "N5V2M8",
        				 "PHONE" : "5194528180",
        				 "FAX" : "5194528189",
        				 "WEB" : "http://www.tvdsb.ca/EvelynHarrison.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Evelyn Harrison,London",
        				 "Rating2011_12" : "1.4", 
        				 "Rating_in_the_most_recent_five_years" : "4.1", 
        				 "Rank2011_12" : "2676/2714",
        				 "Rank_in_the_most_recent_five_years" : "2025/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1656,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.8561783,43.2418404]},
        		"properties" : { 
        				 "NAME" : "George L Armstrong", 
        				 "MUNICIPALITY" : "Hamilton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "460 Concession Street", 
        				 "POSTALCODE" : "L9A1C3",
        				 "PHONE" : "9053855337",
        				 "FAX" : "9053858996",
        				 "WEB" : "www.hwdsb.on.ca/georgelarmstrong",
        				 "BOARD_NAME" : "Hamilton-Wentworth DSB",
        				 "ProvincalName" : "George L Armstrong,Hamilton",
        				 "Rating2011_12" : "1.5", 
        				 "Rating_in_the_most_recent_five_years" : "2.7", 
        				 "Rank2011_12" : "2667/2714",
        				 "Rank_in_the_most_recent_five_years" : "2206/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1680,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-74.718338,45.0277596]},
        		"properties" : { 
        				 "NAME" : "Gladstone", 
        				 "MUNICIPALITY" : "Cornwall", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "825 McConnell Avenue", 
        				 "POSTALCODE" : "K6H4M5",
        				 "PHONE" : "6139325650",
        				 "FAX" : "6139362128",
        				 "WEB" : "http://www.ucdsb.on.ca/Schools/School+Directory/Elementary/GLD/homepage.htm",
        				 "BOARD_NAME" : "Upper Canada DSB",
        				 "ProvincalName" : "Gladstone,Cornwall",
        				 "Rating2011_12" : "1.9", 
        				 "Rating_in_the_most_recent_five_years" : "4.3", 
        				 "Rank2011_12" : "2645/2714",
        				 "Rank_in_the_most_recent_five_years" : "1977/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1756,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.2688599,43.1532707]},
        		"properties" : { 
        				 "NAME" : "Graham Bell-Victoria", 
        				 "MUNICIPALITY" : "Brantford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "56 Grand St", 
        				 "POSTALCODE" : "N3R4B2",
        				 "PHONE" : "5197524723",
        				 "FAX" : "5197524727",
        				 "WEB" : "http://granderie.ca/gbv/",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Graham Bell-Victoria,Brantford",
        				 "Rating2011_12" : "1.3", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2680/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1825,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4326935,44.5985069]},
        		"properties" : { 
        				 "NAME" : "Harriett Todd", 
        				 "MUNICIPALITY" : "Orillia", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "11 George St", 
        				 "POSTALCODE" : "L3V2V1",
        				 "PHONE" : "7053259388",
        				 "FAX" : "7053292101",
        				 "WEB" : "http://har.scdsb.on.ca",
        				 "BOARD_NAME" : "Simcoe County DSB",
        				 "ProvincalName" : "Harriett Todd,Orillia",
        				 "Rating2011_12" : "2", 
        				 "Rating_in_the_most_recent_five_years" : "2.6", 
        				 "Rank2011_12" : "2639/2714",
        				 "Rank_in_the_most_recent_five_years" : "2218/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1889,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-82.3715134,42.9820137]},
        		"properties" : { 
        				 "NAME" : "High Park", 
        				 "MUNICIPALITY" : "Sarnia", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "757 Kember Ave", 
        				 "POSTALCODE" : "N7S2T3",
        				 "PHONE" : "5193320474",
        				 "FAX" : "5193328643",
        				 "WEB" : "http://highpark.lkdsb.net/",
        				 "BOARD_NAME" : "Lambton Kent DSB",
        				 "ProvincalName" : "High Park,Sarnia",
        				 "Rating2011_12" : "1.7", 
        				 "Rating_in_the_most_recent_five_years" : "2.9", 
        				 "Rank2011_12" : "2659/2714",
        				 "Rank_in_the_most_recent_five_years" : "2189/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1902,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2237015,43.0222015]},
        		"properties" : { 
        				 "NAME" : "Hillcrest", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1231 Fuller St", 
        				 "POSTALCODE" : "N5Y4P7",
        				 "PHONE" : "5194528220",
        				 "FAX" : "5194528229",
        				 "WEB" : "http://www.tvdsb.ca/Hillcrest-London.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Hillcrest,London",
        				 "Rating2011_12" : "2", 
        				 "Rating_in_the_most_recent_five_years" : "4", 
        				 "Rank2011_12" : "2639/2714",
        				 "Rank_in_the_most_recent_five_years" : "2038/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2128,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-83.0549622,42.3084793]},
        		"properties" : { 
        				 "NAME" : "J E Benson", 
        				 "MUNICIPALITY" : "Windsor", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1556 Wyandotte St W", 
        				 "POSTALCODE" : "N9B1H5",
        				 "PHONE" : "5192543761",
        				 "FAX" : "5192543321",
        				 "WEB" : "http://www.gecdsb.on.ca/schools/ELEM/benson/index.htm",
        				 "BOARD_NAME" : "Greater Essex County DSB",
        				 "ProvincalName" : "J E Benson,Windsor",
        				 "Rating2011_12" : "1.8", 
        				 "Rating_in_the_most_recent_five_years" : "2.6", 
        				 "Rank2011_12" : "2655/2714",
        				 "Rank_in_the_most_recent_five_years" : "2218/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2131,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4597321,44.2135696]},
        		"properties" : { 
        				 "NAME" : "Jersey", 
        				 "MUNICIPALITY" : "Keswick", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "176 Glenwoods Ave.", 
        				 "POSTALCODE" : "L4P3E9",
        				 "PHONE" : "9054767777",
        				 "FAX" : "9054764961",
        				 "WEB" : "http://www.jersey.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "Jersey,Keswick",
        				 "Rating2011_12" : "1.4", 
        				 "Rating_in_the_most_recent_five_years" : "3.4", 
        				 "Rank2011_12" : "2676/2714",
        				 "Rank_in_the_most_recent_five_years" : "2146/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2263,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.2480087,43.1454506]},
        		"properties" : { 
        				 "NAME" : "King George", 
        				 "MUNICIPALITY" : "Brantford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "265 Rawdon St", 
        				 "POSTALCODE" : "N3S6G7",
        				 "PHONE" : "5197527486",
        				 "FAX" : "5197521015",
        				 "WEB" : "http://www.granderie.ca/Schools/SchoolDirectory/Elementary/tabid/120/mid/593/SchoolID/44/ctl/Details/Default.aspx",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "King George,Brantford",
        				 "Rating2011_12" : "1.2", 
        				 "Rating_in_the_most_recent_five_years" : "1.1", 
        				 "Rank2011_12" : "2683/2714",
        				 "Rank_in_the_most_recent_five_years" : "2264/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2257,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.8281021,43.2514381]},
        		"properties" : { 
        				 "NAME" : "King George", 
        				 "MUNICIPALITY" : "Hamilton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "77 Gage Avenue North", 
        				 "POSTALCODE" : "L8L6Z8",
        				 "PHONE" : "9055492224",
        				 "FAX" : "9055494350",
        				 "WEB" : "http://www.hwdsb.on.ca/schools/schoolprofiles/index.aspx?school_id=kinggeorge",
        				 "BOARD_NAME" : "Hamilton-Wentworth DSB",
        				 "ProvincalName" : "King George,Hamilton",
        				 "Rating2011_12" : "1.4", 
        				 "Rating_in_the_most_recent_five_years" : "1.5", 
        				 "Rank2011_12" : "2676/2714",
        				 "Rank_in_the_most_recent_five_years" : "2258/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2288,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2298965,43.0071983]},
        		"properties" : { 
        				 "NAME" : "Knollwood Park", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "70 Gammage St", 
        				 "POSTALCODE" : "N5Y2B1",
        				 "PHONE" : "5194528290",
        				 "FAX" : "5194528299",
        				 "WEB" : "http://www.tvdsb.ca/KnollwoodPark.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Knollwood Park,London",
        				 "Rating2011_12" : "1.9", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2645/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2336,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-82.371048,42.9701881]},
        		"properties" : { 
        				 "NAME" : "Lansdowne", 
        				 "MUNICIPALITY" : "Sarnia", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "95 Lansdowne Ave", 
        				 "POSTALCODE" : "N7S1G7",
        				 "PHONE" : "5193362111",
        				 "FAX" : "5193362306",
        				 "WEB" : "http://lansdowne.lkdsb.net/",
        				 "BOARD_NAME" : "Lambton Kent DSB",
        				 "ProvincalName" : "Lansdowne,Sarnia",
        				 "Rating2011_12" : "1.7", 
        				 "Rating_in_the_most_recent_five_years" : "2.7", 
        				 "Rank2011_12" : "2659/2714",
        				 "Rank_in_the_most_recent_five_years" : "2206/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2337,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.0027161,46.497448]},
        		"properties" : { 
        				 "NAME" : "Lansdowne", 
        				 "MUNICIPALITY" : "Sudbury", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "185 Lansdowne St", 
        				 "POSTALCODE" : "P3C4M1",
        				 "PHONE" : "7056756451",
        				 "FAX" : "7056881551",
        				 "WEB" : "http://www.rainbowschools.ca/schools/landsdownePS/index.php",
        				 "BOARD_NAME" : "Rainbow DSB",
        				 "ProvincalName" : "Lansdowne,Sudbury",
        				 "Rating2011_12" : "1.2", 
        				 "Rating_in_the_most_recent_five_years" : "1.6", 
        				 "Rank2011_12" : "2683/2714",
        				 "Rank_in_the_most_recent_five_years" : "2256/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2418,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2246017,43.0135994]},
        		"properties" : { 
        				 "NAME" : "Lord Elgin", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1100 Victoria Dr", 
        				 "POSTALCODE" : "N5Y4E2",
        				 "PHONE" : "5194528310",
        				 "FAX" : "5194528319",
        				 "WEB" : "http://www.tvdsb.ca/LordElgin.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Lord Elgin,London",
        				 "Rating2011_12" : "1.9", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2645/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2420,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.1675034,42.9990997]},
        		"properties" : { 
        				 "NAME" : "Lord Nelson", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1990 Royal Cres", 
        				 "POSTALCODE" : "N5V1N8",
        				 "PHONE" : "5194528320",
        				 "FAX" : "5194528329",
        				 "WEB" : "http://www.tvdsb.ca/LordNelson.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Lord Nelson,London",
        				 "Rating2011_12" : "1.5", 
        				 "Rating_in_the_most_recent_five_years" : "2.4", 
        				 "Rank2011_12" : "2667/2714",
        				 "Rank_in_the_most_recent_five_years" : "2230/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1165,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.6310959,45.3989906]},
        		"properties" : { 
        				 "NAME" : "Marie-Curie", 
        				 "MUNICIPALITY" : "Ottawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "French", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "860 avenue Colson", 
        				 "POSTALCODE" : "K1G1R7",
        				 "PHONE" : "6135234975",
        				 "FAX" : "6135239108",
        				 "WEB" : "http://www.marie-curie.cepeo.on.ca",
        				 "BOARD_NAME" : "CƒP de l'Est de l'Ontario",
        				 "ProvincalName" : "Marie-Curie,Ottawa",
        				 "Rating2011_12" : "1.9", 
        				 "Rating_in_the_most_recent_five_years" : "3.1", 
        				 "Rank2011_12" : "2645/2714",
        				 "Rank_in_the_most_recent_five_years" : "2173/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2557,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-89.2490158,48.3873787]},
        		"properties" : { 
        				 "NAME" : "McKellar Park Central", 
        				 "MUNICIPALITY" : "Thunder Bay", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "301 North Archibald St", 
        				 "POSTALCODE" : "P7C3Y3",
        				 "PHONE" : "8076232289",
        				 "FAX" : "8076231586",
        				 "WEB" : "http://www.lakeheadschools.ca/mckellar",
        				 "BOARD_NAME" : "Lakehead DSB",
        				 "ProvincalName" : "McKellar Park Central,Thunder Bay",
        				 "Rating2011_12" : "2", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2639/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2773,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.7558365,43.1404419]},
        		"properties" : { 
        				 "NAME" : "Northdale", 
        				 "MUNICIPALITY" : "Woodstock", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "290 Victoria St N", 
        				 "POSTALCODE" : "N4S6W5",
        				 "PHONE" : "5195375761",
        				 "FAX" : "5195371088",
        				 "WEB" : "http://www.tvdsb.ca/NorthdaleWoodstock.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Northdale,Woodstock",
        				 "Rating2011_12" : "1.6", 
        				 "Rating_in_the_most_recent_five_years" : "4.3", 
        				 "Rank2011_12" : "2661/2714",
        				 "Rank_in_the_most_recent_five_years" : "1977/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3149,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.6912308,44.4876671]},
        		"properties" : { 
        				 "NAME" : "Prince Charles", 
        				 "MUNICIPALITY" : "Verona", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "100", 
        				 "STREET" : "6875 Highway 38", 
        				 "POSTALCODE" : "K0H2W0",
        				 "PHONE" : "6133742003",
        				 "FAX" : "6133741878",
        				 "WEB" : "http://www.limestone.on.ca/schools/elementary/princ_profile",
        				 "BOARD_NAME" : "Limestone DSB",
        				 "ProvincalName" : "Prince Charles,Verona",
        				 "Rating2011_12" : "1.5", 
        				 "Rating_in_the_most_recent_five_years" : "1.8", 
        				 "Rank2011_12" : "2667/2714",
        				 "Rank_in_the_most_recent_five_years" : "2246/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3156,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.8321915,43.2512283]},
        		"properties" : { 
        				 "NAME" : "Prince of Wales", 
        				 "MUNICIPALITY" : "Hamilton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "77 Melrose Avenue North", 
        				 "POSTALCODE" : "L8L6X4",
        				 "PHONE" : "9056675870",
        				 "FAX" : "",
        				 "WEB" : "http://www.hwdsb.on.ca/schools/principals.aspx?type=Secondary",
        				 "BOARD_NAME" : "Hamilton-Wentworth DSB",
        				 "ProvincalName" : "Prince of Wales,Hamilton",
        				 "Rating2011_12" : "1.9", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2645/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3169,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2209015,42.9682007]},
        		"properties" : { 
        				 "NAME" : "Princess Elizabeth", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "247 Thompson Rd", 
        				 "POSTALCODE" : "N5Z2Z3",
        				 "PHONE" : "5194528490",
        				 "FAX" : "5194528499",
        				 "WEB" : "http://www.tvdsb.ca/Elizabeth.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Princess Elizabeth,London",
        				 "Rating2011_12" : "1.3", 
        				 "Rating_in_the_most_recent_five_years" : "1.3", 
        				 "Rank2011_12" : "2680/2714",
        				 "Rank_in_the_most_recent_five_years" : "2261/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3192,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.145256,44.0100746]},
        		"properties" : { 
        				 "NAME" : "Queen Elizabeth", 
        				 "MUNICIPALITY" : "Picton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "35 Barker St", 
        				 "POSTALCODE" : "K0K2T0",
        				 "PHONE" : "6134766475",
        				 "FAX" : "6134766490",
        				 "WEB" : "http://edu.hpedsb.on.ca/qep/",
        				 "BOARD_NAME" : "Hastings & Prince Edward DSB",
        				 "ProvincalName" : "Queen Elizabeth,Picton",
        				 "Rating2011_12" : "2", 
        				 "Rating_in_the_most_recent_five_years" : "1.8", 
        				 "Rank2011_12" : "2639/2714",
        				 "Rank_in_the_most_recent_five_years" : "2246/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3186,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.9960022,46.5061646]},
        		"properties" : { 
        				 "NAME" : "Queen Elizabeth II", 
        				 "MUNICIPALITY" : "Sudbury", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "32 Dell St", 
        				 "POSTALCODE" : "P3C2X8",
        				 "PHONE" : "7056756198",
        				 "FAX" : "7056751784",
        				 "WEB" : "http://www.rainbowschools.ca/elementary/queen_elizabeth/index.php",
        				 "BOARD_NAME" : "Rainbow DSB",
        				 "ProvincalName" : "Queen Elizabeth II,Sudbury",
        				 "Rating2011_12" : "1.5", 
        				 "Rating_in_the_most_recent_five_years" : "2.5", 
        				 "Rank2011_12" : "2667/2714",
        				 "Rank_in_the_most_recent_five_years" : "2225/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3187,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-82.3735962,42.9712296]},
        		"properties" : { 
        				 "NAME" : "Queen Elizabeth II", 
        				 "MUNICIPALITY" : "Sarnia", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "60 Aberdeen Ave", 
        				 "POSTALCODE" : "N7S2N8",
        				 "PHONE" : "5193440801",
        				 "FAX" : "5193324057",
        				 "WEB" : "http://queenelizabeths.lkdsb.net/",
        				 "BOARD_NAME" : "Lambton Kent DSB",
        				 "ProvincalName" : "Queen Elizabeth II,Sarnia",
        				 "Rating2011_12" : "1.6", 
        				 "Rating_in_the_most_recent_five_years" : "1.7", 
        				 "Rank2011_12" : "2661/2714",
        				 "Rank_in_the_most_recent_five_years" : "2250/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3239,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3642807,43.6579399]},
        		"properties" : { 
        				 "NAME" : "Regent Park/Duke of York", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "20 Regent St", 
        				 "POSTALCODE" : "M5A3N6",
        				 "PHONE" : "4163931730",
        				 "FAX" : "4163931724",
        				 "WEB" : "http://www.tdsb.on.ca/SchoolWeb/_site/viewitem.asp?siteid=10379&pageid=18943&menuid=21749",
        				 "BOARD_NAME" : "Toronto DSB",
        				 "ProvincalName" : "Regent Park/Duke of York,Toronto",
        				 "Rating2011_12" : "1.1", 
        				 "Rating_in_the_most_recent_five_years" : "1.7", 
        				 "Rank2011_12" : "2686/2714",
        				 "Rank_in_the_most_recent_five_years" : "2250/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3289,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-78.8503876,43.8920708]},
        		"properties" : { 
        				 "NAME" : "Ritson", 
        				 "MUNICIPALITY" : "Oshawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "300 Ritson Rd S", 
        				 "POSTALCODE" : "L1H5J1",
        				 "PHONE" : "9057234133",
        				 "FAX" : "9057234542",
        				 "WEB" : "http://ritson.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "Ritson,Oshawa",
        				 "Rating2011_12" : "1.5", 
        				 "Rating_in_the_most_recent_five_years" : "2.7", 
        				 "Rank2011_12" : "2667/2714",
        				 "Rank_in_the_most_recent_five_years" : "2206/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3368,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-82.9467163,42.3064919]},
        		"properties" : { 
        				 "NAME" : "Roseville", 
        				 "MUNICIPALITY" : "Windsor", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "6265 Roseville Garden Dr", 
        				 "POSTALCODE" : "N8T3B9",
        				 "PHONE" : "5199443611",
        				 "FAX" : "5199443973",
        				 "WEB" : "http://www.gecdsb.on.ca/schools/elem/rosevill",
        				 "BOARD_NAME" : "Greater Essex County DSB",
        				 "ProvincalName" : "Roseville,Windsor",
        				 "Rating2011_12" : "1.6", 
        				 "Rating_in_the_most_recent_five_years" : "3", 
        				 "Rank2011_12" : "2661/2714",
        				 "Rank_in_the_most_recent_five_years" : "2179/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1312,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.9468765,46.6511917]},
        		"properties" : { 
        				 "NAME" : "s_par_e Notre-Dame", 
        				 "MUNICIPALITY" : "Hanmer", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "French", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "4503 rue Dennie", 
        				 "POSTALCODE" : "P3P1L1",
        				 "PHONE" : "7059694411",
        				 "FAX" : "7059694412",
        				 "WEB" : "www.nouvelon.ca/nos_ecoles/ecole.php?ecole=ndh",
        				 "BOARD_NAME" : "CSDC du Nouvel-Ontario",
        				 "ProvincalName" : "Notre-Dame,Hanmer",
        				 "Rating2011_12" : "1.9", 
        				 "Rating_in_the_most_recent_five_years" : "3.9", 
        				 "Rank2011_12" : "2645/2714",
        				 "Rank_in_the_most_recent_five_years" : "2059/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1335,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4548416,46.3135681]},
        		"properties" : { 
        				 "NAME" : "s_par_e Saint-Vincent", 
        				 "MUNICIPALITY" : "North Bay", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "French", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "124 rue King Est", 
        				 "POSTALCODE" : "P1B1P2",
        				 "PHONE" : "7054746740",
        				 "FAX" : "7054746746",
        				 "WEB" : "http://st-vincent.franco-nord.ca/",
        				 "BOARD_NAME" : "CSDC Franco-Nord",
        				 "ProvincalName" : "Saint-Vincent,North Bay",
        				 "Rating2011_12" : "1.1", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2686/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3526,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-91.9088211,50.1070099]},
        		"properties" : { 
        				 "NAME" : "Sioux Mountain", 
        				 "MUNICIPALITY" : "Sioux Lookout", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 969", 
        				 "STREET" : "89 First St", 
        				 "POSTALCODE" : "P8T1B5",
        				 "PHONE" : "8077373480",
        				 "FAX" : "8077373486",
        				 "WEB" : "http://www.siouxmountain.com/blog/",
        				 "BOARD_NAME" : "Keewatin-Patricia DSB",
        				 "ProvincalName" : "Sioux Mountain,Sioux Lookout",
        				 "Rating2011_12" : "1.4", 
        				 "Rating_in_the_most_recent_five_years" : "1.7", 
        				 "Rank2011_12" : "2676/2714",
        				 "Rank_in_the_most_recent_five_years" : "2250/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3551,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2181015,43.0112991]},
        		"properties" : { 
        				 "NAME" : "Sir John A Macdonald", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1150 Landor St", 
        				 "POSTALCODE" : "N5Y3W3",
        				 "PHONE" : "5194528570",
        				 "FAX" : "5194528579",
        				 "WEB" : "http://www.tvdsb.ca/Macdonald.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Sir John A Macdonald,London",
        				 "Rating2011_12" : "1.8", 
        				 "Rating_in_the_most_recent_five_years" : "1.9", 
        				 "Rank2011_12" : "2655/2714",
        				 "Rank_in_the_most_recent_five_years" : "2244/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3626,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.9304886,42.8305244]},
        		"properties" : { 
        				 "NAME" : "Springfield", 
        				 "MUNICIPALITY" : "Springfield", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "51336 Ron McNeil Line", 
        				 "POSTALCODE" : "N0L2J0",
        				 "PHONE" : "5197654162",
        				 "FAX" : "5197654247",
        				 "WEB" : "http://www.tvdsb.ca/Springfield.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Springfield,Springfield",
        				 "Rating2011_12" : "1", 
        				 "Rating_in_the_most_recent_five_years" : "2.4", 
        				 "Rank2011_12" : "2691/2714",
        				 "Rank_in_the_most_recent_five_years" : "2230/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3673,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.5968323,43.7544212]},
        		"properties" : { 
        				 "NAME" : "St Angela", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "220 Mount Olive Dr", 
        				 "POSTALCODE" : "M9V3Z5",
        				 "PHONE" : "4163935361",
        				 "FAX" : "4163976041",
        				 "WEB" : "http://www.tcdsb.org/stangela/",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "St Angela,Toronto",
        				 "Rating2011_12" : "1.2", 
        				 "Rating_in_the_most_recent_five_years" : "3.5", 
        				 "Rank2011_12" : "2683/2714",
        				 "Rank_in_the_most_recent_five_years" : "2136/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3756,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-82.9853592,42.3064919]},
        		"properties" : { 
        				 "NAME" : "St Bernard", 
        				 "MUNICIPALITY" : "Windsor", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1847 Meldrum Rd", 
        				 "POSTALCODE" : "N8W4E1",
        				 "PHONE" : "5199456948",
        				 "FAX" : "5199459942",
        				 "WEB" : "http://mail.wecdsb.on.ca/~124/",
        				 "BOARD_NAME" : "Windsor-Essex CDSB",
        				 "ProvincalName" : "St Bernard,Windsor",
        				 "Rating2011_12" : "1.9", 
        				 "Rating_in_the_most_recent_five_years" : "3", 
        				 "Rank2011_12" : "2645/2714",
        				 "Rank_in_the_most_recent_five_years" : "2179/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4076,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-82.4374542,42.8783264]},
        		"properties" : { 
        				 "NAME" : "St Joseph", 
        				 "MUNICIPALITY" : "Corunna", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 670", 
        				 "STREET" : "535 Birchbank Drive", 
        				 "POSTALCODE" : "N0N1G0",
        				 "PHONE" : "5198621479",
        				 "FAX" : "5198622330",
        				 "WEB" : "http://www.st-clair.net/schools/school.asp?loc=94",
        				 "BOARD_NAME" : "St Clair CDSB",
        				 "ProvincalName" : "St Joseph,Corunna",
        				 "Rating2011_12" : "1.6", 
        				 "Rating_in_the_most_recent_five_years" : "4", 
        				 "Rank2011_12" : "2661/2714",
        				 "Rank_in_the_most_recent_five_years" : "2038/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4680,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.2346573,43.5450821]},
        		"properties" : { 
        				 "NAME" : "Tytler", 
        				 "MUNICIPALITY" : "Guelph", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "131 Ontario St", 
        				 "POSTALCODE" : "N1E3B3",
        				 "PHONE" : "5198229271",
        				 "FAX" : "5198220936",
        				 "WEB" : "http://www.ugdsb.on.ca/tytler",
        				 "BOARD_NAME" : "Upper Grand DSB",
        				 "ProvincalName" : "Tytler,Guelph",
        				 "Rating2011_12" : "1.5", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2667/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4727,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.0232468,45.3422356]},
        		"properties" : { 
        				 "NAME" : "Victory", 
        				 "MUNICIPALITY" : "Parry Sound", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "15 Forest St", 
        				 "POSTALCODE" : "P2A2R1",
        				 "PHONE" : "7057465691",
        				 "FAX" : "7057467357",
        				 "WEB" : "http://portal.nearnorthschools.ca/sites/schools/victory/Pages/default.aspx",
        				 "BOARD_NAME" : "Near North DSB",
        				 "ProvincalName" : "Victory,Parry Sound",
        				 "Rating2011_12" : "1.1", 
        				 "Rating_in_the_most_recent_five_years" : "2.8", 
        				 "Rank2011_12" : "2686/2714",
        				 "Rank_in_the_most_recent_five_years" : "2199/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4729,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-78.8616486,43.8908806]},
        		"properties" : { 
        				 "NAME" : "Village Union", 
        				 "MUNICIPALITY" : "Oshawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "240 Simcoe St S", 
        				 "POSTALCODE" : "L1H4H4",
        				 "PHONE" : "9057251622",
        				 "FAX" : "9057250259",
        				 "WEB" : "http://villageunion.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "Village Union,Oshawa",
        				 "Rating2011_12" : "1.8", 
        				 "Rating_in_the_most_recent_five_years" : "1.8", 
        				 "Rank2011_12" : "2655/2714",
        				 "Rank_in_the_most_recent_five_years" : "2246/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4941,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.2303925,43.1460114]},
        		"properties" : { 
        				 "NAME" : "Woodman-Cainsville", 
        				 "MUNICIPALITY" : "Brantford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "51 Woodman Dr", 
        				 "POSTALCODE" : "N3S4K3",
        				 "PHONE" : "5197565013",
        				 "FAX" : "5197560984",
        				 "WEB" : "http://www.granderie.ca/woodmanecho/",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Woodman-Cainsville,Brantford",
        				 "Rating2011_12" : "1.3", 
        				 "Rating_in_the_most_recent_five_years" : "2.5", 
        				 "Rank2011_12" : "2680/2714",
        				 "Rank_in_the_most_recent_five_years" : "2225/2268",
        				 "popupContent": "Put more data here" }}
             ]
    };
    