 var schools2 = { 
    "type" : "FeatureCollection",
        "features" : [
             { "type" : "Feature",
        "id" : 64,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-89.2498245,48.4390869]},
        		"properties" : { 
        				 "NAME" : "Algonquin Avenue", 
        				 "MUNICIPALITY" : "Thunder Bay", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "160 South Algonquin Ave", 
        				 "POSTALCODE" : "P7B4T1",
        				 "PHONE" : "8077673881",
        				 "FAX" : "8077675341",
        				 "WEB" : "http://www.lakeheadschools.ca/algonquin/",
        				 "BOARD_NAME" : "Lakehead DSB",
        				 "ProvincalName" : "Algonquin Avenue,Thunder Bay",
        				 "Rating2011_12" : "2.3", 
        				 "Rating_in_the_most_recent_five_years" : "5", 
        				 "Rank2011_12" : "2617/2714",
        				 "Rank_in_the_most_recent_five_years" : "1724/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 255,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.8622589,43.2675056]},
        		"properties" : { 
        				 "NAME" : "Bennetto", 
        				 "MUNICIPALITY" : "Hamilton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "47 Simcoe Street East", 
        				 "POSTALCODE" : "L8L3N2",
        				 "PHONE" : "9055286341",
        				 "FAX" : "9055286097",
        				 "WEB" : "www.hwdsb.on.ca/bennetto",
        				 "BOARD_NAME" : "Hamilton-Wentworth DSB",
        				 "ProvincalName" : "Bennetto,Hamilton",
        				 "Rating2011_12" : "2.5", 
        				 "Rating_in_the_most_recent_five_years" : "2.7", 
        				 "Rank2011_12" : "2606/2714",
        				 "Rank_in_the_most_recent_five_years" : "2206/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 343,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-78.8401794,43.8734512]},
        		"properties" : { 
        				 "NAME" : "Bobby Orr", 
        				 "MUNICIPALITY" : "Oshawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "7 Waterloo St", 
        				 "POSTALCODE" : "L1H8V9",
        				 "PHONE" : "9057233621",
        				 "FAX" : "",
        				 "WEB" : "http://bobbyorr.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "Bobby Orr,Oshawa",
        				 "Rating2011_12" : "2.8", 
        				 "Rating_in_the_most_recent_five_years" : "3.7", 
        				 "Rank2011_12" : "2569/2714",
        				 "Rank_in_the_most_recent_five_years" : "2105/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 347,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.1559982,43.0055008]},
        		"properties" : { 
        				 "NAME" : "Bonaventure Meadows", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "141 Bonaventure Dr", 
        				 "POSTALCODE" : "N5V4S6",
        				 "PHONE" : "5194528060",
        				 "FAX" : "5194528069",
        				 "WEB" : "http://www.tvdsb.ca/Bonaventure.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Bonaventure Meadows,London",
        				 "Rating2011_12" : "2.1", 
        				 "Rating_in_the_most_recent_five_years" : "3", 
        				 "Rank2011_12" : "2630/2714",
        				 "Rank_in_the_most_recent_five_years" : "2179/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 429,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.4294662,43.097271]},
        		"properties" : { 
        				 "NAME" : "Burford District", 
        				 "MUNICIPALITY" : "Burford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 130", 
        				 "STREET" : "35 Alexander St", 
        				 "POSTALCODE" : "N0E1A0",
        				 "PHONE" : "5194492457",
        				 "FAX" : "5194495314",
        				 "WEB" : "http://granderie.ca/burforddes/",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Burford District,Burford",
        				 "Rating2011_12" : "2.7", 
        				 "Rating_in_the_most_recent_five_years" : "4.3", 
        				 "Rank2011_12" : "2583/2714",
        				 "Rank_in_the_most_recent_five_years" : "1977/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 523,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2115555,42.9632988]},
        		"properties" : { 
        				 "NAME" : "C C Carrothers", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "360 Chippendale Cres", 
        				 "POSTALCODE" : "N5Z3G2",
        				 "PHONE" : "5194528110",
        				 "FAX" : "5194528119",
        				 "WEB" : "http://www.tvdsb.ca/Carrothers.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "C C Carrothers,London",
        				 "Rating2011_12" : "2.7", 
        				 "Rating_in_the_most_recent_five_years" : "3.2", 
        				 "Rank2011_12" : "2583/2714",
        				 "Rank_in_the_most_recent_five_years" : "2164/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 497,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.2121124,43.185463]},
        		"properties" : { 
        				 "NAME" : "Carleton", 
        				 "MUNICIPALITY" : "St Catharines", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1 Carlton Park Dr", 
        				 "POSTALCODE" : "L2M4M9",
        				 "PHONE" : "9059345243",
        				 "FAX" : "9059346202",
        				 "WEB" : "http://www.dsbn.edu.on.ca/Schools/Carleton/",
        				 "BOARD_NAME" : "DSB Niagara",
        				 "ProvincalName" : "Carleton,St Catharines",
        				 "Rating2011_12" : "2.7", 
        				 "Rating_in_the_most_recent_five_years" : "6.1", 
        				 "Rank2011_12" : "2583/2714",
        				 "Rank_in_the_most_recent_five_years" : "1169/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 533,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.2621002,43.1841316]},
        		"properties" : { 
        				 "NAME" : "Cedarland", 
        				 "MUNICIPALITY" : "Brantford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "60 Ashgrove Ave", 
        				 "POSTALCODE" : "N3R6E5",
        				 "PHONE" : "5197529610",
        				 "FAX" : "5197527792",
        				 "WEB" : "http://granderie.ca/cedarland/",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Cedarland,Brantford",
        				 "Rating2011_12" : "2.7", 
        				 "Rating_in_the_most_recent_five_years" : "3.1", 
        				 "Rank2011_12" : "2583/2714",
        				 "Rank_in_the_most_recent_five_years" : "2173/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 612,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.6607132,45.375061]},
        		"properties" : { 
        				 "NAME" : "Charles H. Hulse", 
        				 "MUNICIPALITY" : "Ottawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2605 Alta Vista Dr", 
        				 "POSTALCODE" : "K1V7T3",
        				 "PHONE" : "6135218535",
        				 "FAX" : "6135211477",
        				 "WEB" : "http://www.charleshhulseps.ocdsb.ca/",
        				 "BOARD_NAME" : "Ottawa-Carleton DSB",
        				 "ProvincalName" : "Charles H. Hulse,Ottawa",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "3.2", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "2164/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 645,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.3078079,43.3879814]},
        		"properties" : { 
        				 "NAME" : "Christ The King", 
        				 "MUNICIPALITY" : "Cambridge", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "70 Acorn Way", 
        				 "POSTALCODE" : "N1R8M5",
        				 "PHONE" : "5196216680",
        				 "FAX" : "5196219262",
        				 "WEB" : "http://christtheking.wcdsb.ca",
        				 "BOARD_NAME" : "Waterloo CDSB",
        				 "ProvincalName" : "Christ The King,Cambridge",
        				 "Rating2011_12" : "2.8", 
        				 "Rating_in_the_most_recent_five_years" : "4.9", 
        				 "Rank2011_12" : "2569/2714",
        				 "Rank_in_the_most_recent_five_years" : "1762/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 724,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.7260513,45.4002304]},
        		"properties" : { 
        				 "NAME" : "Connaught", 
        				 "MUNICIPALITY" : "Ottawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1149 Gladstone Ave", 
        				 "POSTALCODE" : "K1Y3H7",
        				 "PHONE" : "6137284671",
        				 "FAX" : "6137289761",
        				 "WEB" : "http://www.connaughtps.ocdsb.ca/",
        				 "BOARD_NAME" : "Ottawa-Carleton DSB",
        				 "ProvincalName" : "Connaught,Ottawa",
        				 "Rating2011_12" : "2.8", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2569/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 874,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-78.8509598,43.8658714]},
        		"properties" : { 
        				 "NAME" : "Dr C F Cannon", 
        				 "MUNICIPALITY" : "Oshawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1196 Cedar St", 
        				 "POSTALCODE" : "L1J3S2",
        				 "PHONE" : "9057250344",
        				 "FAX" : "9057258233",
        				 "WEB" : "http://cannon.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "Dr C F Cannon,Oshawa",
        				 "Rating2011_12" : "2", 
        				 "Rating_in_the_most_recent_five_years" : "2.6", 
        				 "Rank2011_12" : "2639/2714",
        				 "Rank_in_the_most_recent_five_years" : "2218/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1553,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.5017853,44.2430687]},
        		"properties" : { 
        				 "NAME" : "First Avenue", 
        				 "MUNICIPALITY" : "Kingston", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "85 First Ave", 
        				 "POSTALCODE" : "K7K2G7",
        				 "PHONE" : "6135424392",
        				 "FAX" : "6135423980",
        				 "WEB" : "http://firstave.limestone.on.ca/",
        				 "BOARD_NAME" : "Limestone DSB",
        				 "ProvincalName" : "First Avenue,Kingston",
        				 "Rating2011_12" : "2.1", 
        				 "Rating_in_the_most_recent_five_years" : "3.4", 
        				 "Rank2011_12" : "2630/2714",
        				 "Rank_in_the_most_recent_five_years" : "2146/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1607,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-83.0220184,42.3207207]},
        		"properties" : { 
        				 "NAME" : "Frank W Begley", 
        				 "MUNICIPALITY" : "Windsor", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1093 Assumption St", 
        				 "POSTALCODE" : "N9A3C5",
        				 "PHONE" : "5192543217",
        				 "FAX" : "5192543515",
        				 "WEB" : "http://www.gecdsb.on.ca/schools/elem/begley",
        				 "BOARD_NAME" : "Greater Essex County DSB",
        				 "ProvincalName" : "Frank W Begley,Windsor",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "4.1", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "2025/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1600,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.193985,43.0096664]},
        		"properties" : { 
        				 "NAME" : "Franklin D Roosevelt", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "560 Second St", 
        				 "POSTALCODE" : "N5V2B7",
        				 "PHONE" : "5194528190",
        				 "FAX" : "5194528199",
        				 "WEB" : "http://www.tvdsb.ca/FDR.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Franklin D Roosevelt,London",
        				 "Rating2011_12" : "2.5", 
        				 "Rating_in_the_most_recent_five_years" : "3.9", 
        				 "Rank2011_12" : "2606/2714",
        				 "Rank_in_the_most_recent_five_years" : "2059/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1150,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.6352615,45.3490982]},
        		"properties" : { 
        				 "NAME" : "Gabrielle-Roy", 
        				 "MUNICIPALITY" : "Gloucester", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "French", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "3395 avenue Daoust", 
        				 "POSTALCODE" : "K1T4A8",
        				 "PHONE" : "6137338301",
        				 "FAX" : "6137331894",
        				 "WEB" : "www.gabrielle-roy.cepeo.on.ca",
        				 "BOARD_NAME" : "CƒP de l'Est de l'Ontario",
        				 "ProvincalName" : "Gabrielle-Roy,Gloucester",
        				 "Rating2011_12" : "2.9", 
        				 "Rating_in_the_most_recent_five_years" : "3.3", 
        				 "Rank2011_12" : "2559/2714",
        				 "Rank_in_the_most_recent_five_years" : "2156/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1647,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4639664,43.6790619]},
        		"properties" : { 
        				 "NAME" : "General Mercer", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "30 Turnberry Ave", 
        				 "POSTALCODE" : "M6N1P8",
        				 "PHONE" : "4163931414",
        				 "FAX" : "4163931412",
        				 "WEB" : "http://www.tdsb.on.ca/SchoolWeb/_site/viewitem.asp?siteid=10050&pageid=7460&menuid=8529",
        				 "BOARD_NAME" : "Toronto DSB",
        				 "ProvincalName" : "General Mercer,Toronto",
        				 "Rating2011_12" : "2.5", 
        				 "Rating_in_the_most_recent_five_years" : "2.6", 
        				 "Rank2011_12" : "2606/2714",
        				 "Rank_in_the_most_recent_five_years" : "2218/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1691,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.8842163,45.2965508]},
        		"properties" : { 
        				 "NAME" : "Glen Cairn", 
        				 "MUNICIPALITY" : "Kanata", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "182 Morrena Rd", 
        				 "POSTALCODE" : "K2L1E1",
        				 "PHONE" : "6138362342",
        				 "FAX" : "6138364620",
        				 "WEB" : "http://glencairnps.ocdsb.ca/",
        				 "BOARD_NAME" : "Ottawa-Carleton DSB",
        				 "ProvincalName" : "Glen Cairn,Kanata",
        				 "Rating2011_12" : "2.2", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2625/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1713,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-78.8543091,43.8722305]},
        		"properties" : { 
        				 "NAME" : "Glen Street", 
        				 "MUNICIPALITY" : "Oshawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "929 Glen St", 
        				 "POSTALCODE" : "L1J3T9",
        				 "PHONE" : "9057238821",
        				 "FAX" : "9057239960",
        				 "WEB" : "http://glenstreet.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "Glen Street,Oshawa",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "2", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "2239/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1825,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4326935,44.5985069]},
        		"properties" : { 
        				 "NAME" : "Harriett Todd", 
        				 "MUNICIPALITY" : "Orillia", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "11 George St", 
        				 "POSTALCODE" : "L3V2V1",
        				 "PHONE" : "7053259388",
        				 "FAX" : "7053292101",
        				 "WEB" : "http://har.scdsb.on.ca",
        				 "BOARD_NAME" : "Simcoe County DSB",
        				 "ProvincalName" : "Harriett Todd,Orillia",
        				 "Rating2011_12" : "2", 
        				 "Rating_in_the_most_recent_five_years" : "2.6", 
        				 "Rank2011_12" : "2639/2714",
        				 "Rank_in_the_most_recent_five_years" : "2218/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1902,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2237015,43.0222015]},
        		"properties" : { 
        				 "NAME" : "Hillcrest", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1231 Fuller St", 
        				 "POSTALCODE" : "N5Y4P7",
        				 "PHONE" : "5194528220",
        				 "FAX" : "5194528229",
        				 "WEB" : "http://www.tvdsb.ca/Hillcrest-London.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Hillcrest,London",
        				 "Rating2011_12" : "2", 
        				 "Rating_in_the_most_recent_five_years" : "4", 
        				 "Rank2011_12" : "2639/2714",
        				 "Rank_in_the_most_recent_five_years" : "2038/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2056,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-83.0259018,42.3166809]},
        		"properties" : { 
        				 "NAME" : "Immaculate Conception", 
        				 "MUNICIPALITY" : "Windsor", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "735 Tuscarora St", 
        				 "POSTALCODE" : "N9A3M7",
        				 "PHONE" : "5192569156",
        				 "FAX" : "5192560792",
        				 "WEB" : "http://mail.wecdsb.on.ca/~111/",
        				 "BOARD_NAME" : "Windsor-Essex CDSB",
        				 "ProvincalName" : "Immaculate Conception,Windsor",
        				 "Rating2011_12" : "2.4", 
        				 "Rating_in_the_most_recent_five_years" : "3.3", 
        				 "Rank2011_12" : "2612/2714",
        				 "Rank_in_the_most_recent_five_years" : "2156/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2069,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.6985321,43.209301]},
        		"properties" : { 
        				 "NAME" : "Innerkip Central", 
        				 "MUNICIPALITY" : "Innerkip", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 40", 
        				 "STREET" : "180 Coleman St", 
        				 "POSTALCODE" : "N0J1M0",
        				 "PHONE" : "5194693698",
        				 "FAX" : "5194693008",
        				 "WEB" : "http://www.tvdsb.ca/InnerkipCentral.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Innerkip Central,Innerkip",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "6.1", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "1169/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2133,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.5042725,43.4399681]},
        		"properties" : { 
        				 "NAME" : "J F Carmichael", 
        				 "MUNICIPALITY" : "Kitchener", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "80 Patricia Ave", 
        				 "POSTALCODE" : "N2M1J3",
        				 "PHONE" : "5195788450",
        				 "FAX" : "5195785800",
        				 "WEB" : "http://jfc.wrdsb.on.ca/",
        				 "BOARD_NAME" : "Waterloo Region DSB",
        				 "ProvincalName" : "J F Carmichael,Kitchener",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "4.5", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "1924/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2207,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.467514,46.3362045]},
        		"properties" : { 
        				 "NAME" : "J W Trusler", 
        				 "MUNICIPALITY" : "North Bay", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "111 Cartier St", 
        				 "POSTALCODE" : "P1B4Z4",
        				 "PHONE" : "7054725459",
        				 "FAX" : "7054724515",
        				 "WEB" : "http://www.nearnorthschools.ca/schools/",
        				 "BOARD_NAME" : "Near North DSB",
        				 "ProvincalName" : "J W Trusler,North Bay",
        				 "Rating2011_12" : "2.5", 
        				 "Rating_in_the_most_recent_five_years" : "2.9", 
        				 "Rank2011_12" : "2606/2714",
        				 "Rank_in_the_most_recent_five_years" : "2189/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2146,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-83.0064392,42.2998886]},
        		"properties" : { 
        				 "NAME" : "John Campbell", 
        				 "MUNICIPALITY" : "Windsor", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1255 Tecumseh Rd. E.", 
        				 "POSTALCODE" : "N8W1B7",
        				 "PHONE" : "5192546411",
        				 "FAX" : "5192546421",
        				 "WEB" : "http://www.gecdsb.on.ca",
        				 "BOARD_NAME" : "Greater Essex County DSB",
        				 "ProvincalName" : "John Campbell,Windsor",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "3.6", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "2124/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1130,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-83.0069504,42.3112793]},
        		"properties" : { 
        				 "NAME" : "L'Envol_e", 
        				 "MUNICIPALITY" : "Windsor", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "French", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1799 rue Ottawa", 
        				 "POSTALCODE" : "N8Y1R4",
        				 "PHONE" : "5192594860",
        				 "FAX" : "5192594862",
        				 "WEB" : "http://lenvolee.csviamonde.ca",
        				 "BOARD_NAME" : "CS Viamonde",
        				 "ProvincalName" : "L'Envol_e,Windsor",
        				 "Rating2011_12" : "2.8", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2569/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2317,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-94.4886627,49.7918091]},
        		"properties" : { 
        				 "NAME" : "Lakewood", 
        				 "MUNICIPALITY" : "Kenora", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "240 Veterans' Dr", 
        				 "POSTALCODE" : "P9N3Y5",
        				 "PHONE" : "8074683131",
        				 "FAX" : "8074686914",
        				 "WEB" : "http://www.lakewoodpublicschool.com/",
        				 "BOARD_NAME" : "Keewatin-Patricia DSB",
        				 "ProvincalName" : "Lakewood,Kenora",
        				 "Rating2011_12" : "2.2", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2625/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2318,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-78.844162,43.8617249]},
        		"properties" : { 
        				 "NAME" : "Lakewoods", 
        				 "MUNICIPALITY" : "Oshawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "323 Chaleur Ave", 
        				 "POSTALCODE" : "L1J1G5",
        				 "PHONE" : "9055768820",
        				 "FAX" : "9055760314",
        				 "WEB" : "http://lakewoods.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "Lakewoods,Oshawa",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "2.7", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "2206/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2332,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.5820313,42.7399406]},
        		"properties" : { 
        				 "NAME" : "Langton", 
        				 "MUNICIPALITY" : "Langton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 10", 
        				 "STREET" : "23 Albert St", 
        				 "POSTALCODE" : "N0E1G0",
        				 "PHONE" : "5198754448",
        				 "FAX" : "5198754346",
        				 "WEB" : "http://granderie.ca/langtonps",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Langton,Langton",
        				 "Rating2011_12" : "2.1", 
        				 "Rating_in_the_most_recent_five_years" : "3.8", 
        				 "Rank2011_12" : "2630/2714",
        				 "Rank_in_the_most_recent_five_years" : "2083/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2360,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3323669,43.6673203]},
        		"properties" : { 
        				 "NAME" : "Leslieville", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "254 Leslie St", 
        				 "POSTALCODE" : "M4M3C9",
        				 "PHONE" : "4163939480",
        				 "FAX" : "4163930266",
        				 "WEB" : "http://www.tdsb.on.ca/SchoolWeb/_site/viewitem.asp?siteid=10440&pageid=20645&menuid=23833",
        				 "BOARD_NAME" : "Toronto DSB",
        				 "ProvincalName" : "Leslieville,Toronto",
        				 "Rating2011_12" : "2.8", 
        				 "Rating_in_the_most_recent_five_years" : "4.3", 
        				 "Rank2011_12" : "2569/2714",
        				 "Rank_in_the_most_recent_five_years" : "1977/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2405,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.180336,42.7933235]},
        		"properties" : { 
        				 "NAME" : "Lockes", 
        				 "MUNICIPALITY" : "St Thomas", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "22 South Edgeware Rd", 
        				 "POSTALCODE" : "N5P2H2",
        				 "PHONE" : "5196318890",
        				 "FAX" : "5196313229",
        				 "WEB" : "http://www.tvdsb.ca/Locke.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Lockes,St Thomas",
        				 "Rating2011_12" : "2.1", 
        				 "Rating_in_the_most_recent_five_years" : "2.9", 
        				 "Rank2011_12" : "2630/2714",
        				 "Rank_in_the_most_recent_five_years" : "2189/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2417,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.026619,43.8566704]},
        		"properties" : { 
        				 "NAME" : "Lord Elgin", 
        				 "MUNICIPALITY" : "Ajax", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "24 Ontario St", 
        				 "POSTALCODE" : "L1S1T6",
        				 "PHONE" : "9056833581",
        				 "FAX" : "9056833594",
        				 "WEB" : "http://lordelgin.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "Lord Elgin,Ajax",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "4.2", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "2007/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2438,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.5083923,43.9577599]},
        		"properties" : { 
        				 "NAME" : "Lucknow Central", 
        				 "MUNICIPALITY" : "Lucknow", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 208", 
        				 "STREET" : "463 Bob St", 
        				 "POSTALCODE" : "N0G2H0",
        				 "PHONE" : "5195283022",
        				 "FAX" : "5193702938",
        				 "WEB" : "http://www.luc.bwdsb.on.ca",
        				 "BOARD_NAME" : "Bluewater DSB",
        				 "ProvincalName" : "Lucknow Central,Lucknow",
        				 "Rating2011_12" : "2.3", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2617/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2511,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4417572,46.2804527]},
        		"properties" : { 
        				 "NAME" : "Marshall Park", 
        				 "MUNICIPALITY" : "North Bay", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "4 Marshall Park Dr", 
        				 "POSTALCODE" : "P1A2N9",
        				 "PHONE" : "7054752321",
        				 "FAX" : "7054728026",
        				 "WEB" : "http://portal.nearnorthschools.ca/sites/schools/marshallpk/Pages/default.aspx",
        				 "BOARD_NAME" : "Near North DSB",
        				 "ProvincalName" : "Marshall Park,North Bay",
        				 "Rating2011_12" : "2.1", 
        				 "Rating_in_the_most_recent_five_years" : "1.6", 
        				 "Rank2011_12" : "2630/2714",
        				 "Rank_in_the_most_recent_five_years" : "2256/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2548,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.0443115,44.3454628]},
        		"properties" : { 
        				 "NAME" : "McCaskill's Mills", 
        				 "MUNICIPALITY" : "Cannington", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "85 Albert St", 
        				 "POSTALCODE" : "L0E1E0",
        				 "PHONE" : "7054322461",
        				 "FAX" : "7054323255",
        				 "WEB" : "http://mccaskillsmills.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "McCaskill's Mills,Cannington",
        				 "Rating2011_12" : "2.2", 
        				 "Rating_in_the_most_recent_five_years" : "4.5", 
        				 "Rank2011_12" : "2625/2714",
        				 "Rank_in_the_most_recent_five_years" : "1924/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2557,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-89.2490158,48.3873787]},
        		"properties" : { 
        				 "NAME" : "McKellar Park Central", 
        				 "MUNICIPALITY" : "Thunder Bay", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "301 North Archibald St", 
        				 "POSTALCODE" : "P7C3Y3",
        				 "PHONE" : "8076232289",
        				 "FAX" : "8076231586",
        				 "WEB" : "http://www.lakeheadschools.ca/mckellar",
        				 "BOARD_NAME" : "Lakehead DSB",
        				 "ProvincalName" : "McKellar Park Central,Thunder Bay",
        				 "Rating2011_12" : "2", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2639/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2578,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.8204041,43.2428589]},
        		"properties" : { 
        				 "NAME" : "Memorial (City)", 
        				 "MUNICIPALITY" : "Hamilton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1175 Main Street East", 
        				 "POSTALCODE" : "L8M1P3",
        				 "PHONE" : "9055493095",
        				 "FAX" : "9055493105",
        				 "WEB" : "http://fcinternet.hwdsb.on.ca/~memorialweb/",
        				 "BOARD_NAME" : "Hamilton-Wentworth DSB",
        				 "ProvincalName" : "Memorial (City),Hamilton",
        				 "Rating2011_12" : "2.8", 
        				 "Rating_in_the_most_recent_five_years" : "2", 
        				 "Rank2011_12" : "2569/2714",
        				 "Rank_in_the_most_recent_five_years" : "2239/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2663,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.8849258,43.6140556]},
        		"properties" : { 
        				 "NAME" : "Mornington Central", 
        				 "MUNICIPALITY" : "Newton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "7241 Road 131", 
        				 "POSTALCODE" : "N0K1R0",
        				 "PHONE" : "5195958995",
        				 "FAX" : "5195958992",
        				 "WEB" : "http://morningtoncentral.amdsb.ca/",
        				 "BOARD_NAME" : "Avon Maitland DSB",
        				 "ProvincalName" : "Mornington Central,Newton",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2743,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.9671783,44.3591385]},
        		"properties" : { 
        				 "NAME" : "New Lowell Central", 
        				 "MUNICIPALITY" : "New Lowell", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "5197 County Rd 9", 
        				 "POSTALCODE" : "L0M1N0",
        				 "PHONE" : "7054240991",
        				 "FAX" : "7054240012",
        				 "WEB" : "http://nlo.scdsb.on.ca",
        				 "BOARD_NAME" : "Simcoe County DSB",
        				 "ProvincalName" : "New Lowell Central,New Lowell",
        				 "Rating2011_12" : "2.7", 
        				 "Rating_in_the_most_recent_five_years" : "3.6", 
        				 "Rank2011_12" : "2583/2714",
        				 "Rank_in_the_most_recent_five_years" : "2124/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2817,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.6089935,42.9873924]},
        		"properties" : { 
        				 "NAME" : "Norwich", 
        				 "MUNICIPALITY" : "Norwich", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "327", 
        				 "STREET" : "8 Elgin St", 
        				 "POSTALCODE" : "N0J1P0",
        				 "PHONE" : "5198632741",
        				 "FAX" : "5198633128",
        				 "WEB" : "http://www.tvdsb.ca/NorwichPS.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Norwich,Norwich",
        				 "Rating2011_12" : "2.3", 
        				 "Rating_in_the_most_recent_five_years" : "4.2", 
        				 "Rank2011_12" : "2617/2714",
        				 "Rank_in_the_most_recent_five_years" : "2007/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2900,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.6203308,42.959671]},
        		"properties" : { 
        				 "NAME" : "Our Lady Immaculate", 
        				 "MUNICIPALITY" : "Strathroy", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "75 Head St N", 
        				 "POSTALCODE" : "N7G2J6",
        				 "PHONE" : "5196602774",
        				 "FAX" : "5196602774",
        				 "WEB" : "www.ldcsb.on.ca/schools/oli",
        				 "BOARD_NAME" : "London District Board",
        				 "ProvincalName" : "Our Lady Immaculate,Strathroy",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "5.2", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "1641/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2995,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.8432846,43.8307838]},
        		"properties" : { 
        				 "NAME" : "Palmerston", 
        				 "MUNICIPALITY" : "Palmerston", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 430", 
        				 "STREET" : "530 Prospect St", 
        				 "POSTALCODE" : "N0G2P0",
        				 "PHONE" : "5193433520",
        				 "FAX" : "5193432491",
        				 "WEB" : "http://www.ugdsb.on.ca/palmerstonps",
        				 "BOARD_NAME" : "Upper Grand DSB",
        				 "ProvincalName" : "Palmerston,Palmerston",
        				 "Rating2011_12" : "2.4", 
        				 "Rating_in_the_most_recent_five_years" : "3.8", 
        				 "Rank2011_12" : "2612/2714",
        				 "Rank_in_the_most_recent_five_years" : "2083/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3074,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.7868576,45.344326]},
        		"properties" : { 
        				 "NAME" : "Pinecrest", 
        				 "MUNICIPALITY" : "Ottawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1281 Pinecrest Rd", 
        				 "POSTALCODE" : "K2C3E7",
        				 "PHONE" : "6138285115",
        				 "FAX" : "6135963821",
        				 "WEB" : "http://www.pinecrestps.ocdsb.ca/",
        				 "BOARD_NAME" : "Ottawa-Carleton DSB",
        				 "ProvincalName" : "Pinecrest,Ottawa",
        				 "Rating2011_12" : "2.3", 
        				 "Rating_in_the_most_recent_five_years" : "2.5", 
        				 "Rank2011_12" : "2617/2714",
        				 "Rank_in_the_most_recent_five_years" : "2225/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3102,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.246109,42.9828262]},
        		"properties" : { 
        				 "NAME" : "Plymouth", 
        				 "MUNICIPALITY" : "Welland", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "111 First St", 
        				 "POSTALCODE" : "L3B4S1",
        				 "PHONE" : "9057324110",
        				 "FAX" : "9057322728",
        				 "WEB" : "http://www.dsbn.edu.on.ca/Schools/Plymouth/",
        				 "BOARD_NAME" : "DSB Niagara",
        				 "ProvincalName" : "Plymouth,Welland",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3144,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.257103,43.1627235]},
        		"properties" : { 
        				 "NAME" : "Prince Charles", 
        				 "MUNICIPALITY" : "Brantford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "40 Morton Ave", 
        				 "POSTALCODE" : "N3R2N5",
        				 "PHONE" : "5197529687",
        				 "FAX" : "",
        				 "WEB" : "http://granderie.ca/princecharles/",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Prince Charles,Brantford",
        				 "Rating2011_12" : "2.9", 
        				 "Rating_in_the_most_recent_five_years" : "2.4", 
        				 "Rank2011_12" : "2559/2714",
        				 "Rank_in_the_most_recent_five_years" : "2230/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3145,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.1884003,42.9934006]},
        		"properties" : { 
        				 "NAME" : "Prince Charles", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1601 Wavell St", 
        				 "POSTALCODE" : "N5W2C9",
        				 "PHONE" : "5194528470",
        				 "FAX" : "5194528479",
        				 "WEB" : "http://www.tvdsb.ca/PrinceCharles.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Prince Charles,London",
        				 "Rating2011_12" : "2.7", 
        				 "Rating_in_the_most_recent_five_years" : "3.2", 
        				 "Rank2011_12" : "2583/2714",
        				 "Rank_in_the_most_recent_five_years" : "2164/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3148,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.5804596,44.0923004]},
        		"properties" : { 
        				 "NAME" : "Prince Charles", 
        				 "MUNICIPALITY" : "Trenton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "138 Dufferin Ave S", 
        				 "POSTALCODE" : "K8V5E1",
        				 "PHONE" : "6133925461",
        				 "FAX" : "6133924960",
        				 "WEB" : "http://www.hpedsb.on.ca/pct",
        				 "BOARD_NAME" : "Hastings & Prince Edward DSB",
        				 "ProvincalName" : "Prince Charles,Trenton",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "3.4", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "2146/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3151,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-83.0172729,42.3097801]},
        		"properties" : { 
        				 "NAME" : "Prince Edward", 
        				 "MUNICIPALITY" : "Windsor", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "949 Giles Blvd E", 
        				 "POSTALCODE" : "N9A4G2",
        				 "PHONE" : "5192531119",
        				 "FAX" : "5192531609",
        				 "WEB" : "http://www.gecdsb.on.ca/schools/elem/princeed",
        				 "BOARD_NAME" : "Greater Essex County DSB",
        				 "ProvincalName" : "Prince Edward,Windsor",
        				 "Rating2011_12" : "2.9", 
        				 "Rating_in_the_most_recent_five_years" : "4.1", 
        				 "Rank2011_12" : "2559/2714",
        				 "Rank_in_the_most_recent_five_years" : "2025/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3159,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.3838196,44.1805382]},
        		"properties" : { 
        				 "NAME" : "Prince of Wales", 
        				 "MUNICIPALITY" : "Belleville", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "37 Prince of Wales Dr", 
        				 "POSTALCODE" : "K8P2T6",
        				 "PHONE" : "6139688321",
        				 "FAX" : "6139684997",
        				 "WEB" : "http://edu.hpedsb.on.ca/pow/",
        				 "BOARD_NAME" : "Hastings & Prince Edward DSB",
        				 "ProvincalName" : "Prince of Wales,Belleville",
        				 "Rating2011_12" : "2.8", 
        				 "Rating_in_the_most_recent_five_years" : "1.5", 
        				 "Rank2011_12" : "2569/2714",
        				 "Rank_in_the_most_recent_five_years" : "2258/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3166,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.8225937,44.1653175]},
        		"properties" : { 
        				 "NAME" : "Princess Anne", 
        				 "MUNICIPALITY" : "Sudbury", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "500 Douglas St W", 
        				 "POSTALCODE" : "P3C1H7",
        				 "PHONE" : "7056736516",
        				 "FAX" : "7056738967",
        				 "WEB" : "http://www.rainbowschools.ca/elementary/princess_anne/index.php",
        				 "BOARD_NAME" : "Rainbow DSB",
        				 "ProvincalName" : "Princess Anne,Sudbury",
        				 "Rating2011_12" : "2.3", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2617/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3167,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.2595673,43.1244087]},
        		"properties" : { 
        				 "NAME" : "Princess Elizabeth", 
        				 "MUNICIPALITY" : "Brantford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "60 Tecumseh St", 
        				 "POSTALCODE" : "N3S2B5",
        				 "PHONE" : "5197532910",
        				 "FAX" : "5197501100",
        				 "WEB" : "http://granderie.ca/princesselizabeth",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Princess Elizabeth,Brantford",
        				 "Rating2011_12" : "2.3", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2617/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3188,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.4860535,43.430748]},
        		"properties" : { 
        				 "NAME" : "Queen Elizabeth", 
        				 "MUNICIPALITY" : "Kitchener", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "191 Hoffman St", 
        				 "POSTALCODE" : "N2M3N2",
        				 "PHONE" : "5195783910",
        				 "FAX" : "5195782320",
        				 "WEB" : "http://qel.wrdsb.on.ca/",
        				 "BOARD_NAME" : "Waterloo Region DSB",
        				 "ProvincalName" : "Queen Elizabeth,Kitchener",
        				 "Rating2011_12" : "2.9", 
        				 "Rating_in_the_most_recent_five_years" : "3", 
        				 "Rank2011_12" : "2559/2714",
        				 "Rank_in_the_most_recent_five_years" : "2179/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3192,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.145256,44.0100746]},
        		"properties" : { 
        				 "NAME" : "Queen Elizabeth", 
        				 "MUNICIPALITY" : "Picton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "35 Barker St", 
        				 "POSTALCODE" : "K0K2T0",
        				 "PHONE" : "6134766475",
        				 "FAX" : "6134766490",
        				 "WEB" : "http://edu.hpedsb.on.ca/qep/",
        				 "BOARD_NAME" : "Hastings & Prince Edward DSB",
        				 "ProvincalName" : "Queen Elizabeth,Picton",
        				 "Rating2011_12" : "2", 
        				 "Rating_in_the_most_recent_five_years" : "1.8", 
        				 "Rank2011_12" : "2639/2714",
        				 "Rank_in_the_most_recent_five_years" : "2246/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3197,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.5771484,44.1092873]},
        		"properties" : { 
        				 "NAME" : "Queen Elizabeth", 
        				 "MUNICIPALITY" : "Trenton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "16 Sillers Ave", 
        				 "POSTALCODE" : "K8V1X6",
        				 "PHONE" : "6133925004",
        				 "FAX" : "6133924495",
        				 "WEB" : "http://edu.hpedsb.on.ca/qet/",
        				 "BOARD_NAME" : "Hastings & Prince Edward DSB",
        				 "ProvincalName" : "Queen Elizabeth,Trenton",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "3.1", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "2173/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3202,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.641777,45.4266014]},
        		"properties" : { 
        				 "NAME" : "Queen Mary Street", 
        				 "MUNICIPALITY" : "Ottawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "557 Queen Mary St", 
        				 "POSTALCODE" : "K1K1V9",
        				 "PHONE" : "6137491692",
        				 "FAX" : "6137496184",
        				 "WEB" : "http://www.queenmarystreetps.ocdsb.ca/",
        				 "BOARD_NAME" : "Ottawa-Carleton DSB",
        				 "ProvincalName" : "Queen Mary Street,Ottawa",
        				 "Rating2011_12" : "2.2", 
        				 "Rating_in_the_most_recent_five_years" : "1.7", 
        				 "Rank2011_12" : "2625/2714",
        				 "Rank_in_the_most_recent_five_years" : "2250/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3214,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-78.7329025,44.3594627]},
        		"properties" : { 
        				 "NAME" : "Queen Victoria", 
        				 "MUNICIPALITY" : "Lindsay", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "11 John St", 
        				 "POSTALCODE" : "K9V1J3",
        				 "PHONE" : "7053243162",
        				 "FAX" : "7053241066",
        				 "WEB" : "http://qvp.tldsb.on.ca/",
        				 "BOARD_NAME" : "Trillium Lakelands DSB",
        				 "ProvincalName" : "Queen Victoria,Lindsay",
        				 "Rating2011_12" : "2.9", 
        				 "Rating_in_the_most_recent_five_years" : "3.7", 
        				 "Rank2011_12" : "2559/2714",
        				 "Rank_in_the_most_recent_five_years" : "2105/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3392,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.2882309,43.1718903]},
        		"properties" : { 
        				 "NAME" : "Russell Reid", 
        				 "MUNICIPALITY" : "Brantford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "43 Cambridge Dr", 
        				 "POSTALCODE" : "N3R5E3",
        				 "PHONE" : "5197537727",
        				 "FAX" : "5197534699",
        				 "WEB" : "http://granderie.ca/russellreid",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Russell Reid,Brantford",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "4.2", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "2007/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3454,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4776382,43.6809692]},
        		"properties" : { 
        				 "NAME" : "Santa Maria", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "25 Avon Ave", 
        				 "POSTALCODE" : "M6N4X8",
        				 "PHONE" : "4163935368",
        				 "FAX" : "4163935083",
        				 "WEB" : "http://www.tcdsb.org/schools/santamaria.asp",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "Santa Maria,Toronto",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3469,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2965012,48.4745522]},
        		"properties" : { 
        				 "NAME" : "Schumacher", 
        				 "MUNICIPALITY" : "Schumacher", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "Bag 919", 
        				 "STREET" : "64 Croatia Ave", 
        				 "POSTALCODE" : "P0N1G0",
        				 "PHONE" : "7053601780",
        				 "FAX" : "7052675285",
        				 "WEB" : "http://www.dsb1.edu.on.ca/schools/schumacher",
        				 "BOARD_NAME" : "DSB Ontario North East",
        				 "ProvincalName" : "Schumacher,Schumacher",
        				 "Rating2011_12" : "2.2", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2625/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3482,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.93921661,43.2040596]},
        		"properties" : { 
        				 "NAME" : "Seneca Central", 
        				 "MUNICIPALITY" : "York", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2767 Regional Road #9", 
        				 "POSTALCODE" : "N0A1R0",
        				 "PHONE" : "9057725222",
        				 "FAX" : "9057720306",
        				 "WEB" : "http://www.granderie.ca/Schools/SchoolDirectory/Elementary/tabid/120/mid/593/SchoolID/68/ctl/Details/Default.aspx",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Seneca Central,York",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3490,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.9823227,43.3620186]},
        		"properties" : { 
        				 "NAME" : "Shakespeare", 
        				 "MUNICIPALITY" : "Stratford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "35 Mowat St", 
        				 "POSTALCODE" : "N5A2B8",
        				 "PHONE" : "5192713727",
        				 "FAX" : "5192711284",
        				 "WEB" : "http://shakespeare.amdsb.ca/",
        				 "BOARD_NAME" : "Avon Maitland DSB",
        				 "ProvincalName" : "Shakespeare,Stratford",
        				 "Rating2011_12" : "2.8", 
        				 "Rating_in_the_most_recent_five_years" : "5.9", 
        				 "Rank2011_12" : "2569/2714",
        				 "Rank_in_the_most_recent_five_years" : "1283/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3502,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-89.2810822,48.3961258]},
        		"properties" : { 
        				 "NAME" : "Sherbrooke", 
        				 "MUNICIPALITY" : "Thunder Bay", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "110 Sherbrooke St", 
        				 "POSTALCODE" : "P7C4R6",
        				 "PHONE" : "8074754226",
        				 "FAX" : "8074755739",
        				 "WEB" : "http://www.lakeheadschools.ca/sherbrooke",
        				 "BOARD_NAME" : "Lakehead DSB",
        				 "ProvincalName" : "Sherbrooke,Thunder Bay",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3533,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2390976,42.9375992]},
        		"properties" : { 
        				 "NAME" : "Sir Arthur Carty", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1655 Ernest Ave", 
        				 "POSTALCODE" : "N6E2S3",
        				 "PHONE" : "5196602795",
        				 "FAX" : "5196865262",
        				 "WEB" : "http://www.ldcsb.on.ca/schools/carty",
        				 "BOARD_NAME" : "London District Board",
        				 "ProvincalName" : "Sir Arthur Carty,London",
        				 "Rating2011_12" : "2.4", 
        				 "Rating_in_the_most_recent_five_years" : "4.4", 
        				 "Rank2011_12" : "2612/2714",
        				 "Rank_in_the_most_recent_five_years" : "1951/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3616,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.75811,43.1186981]},
        		"properties" : { 
        				 "NAME" : "Southside", 
        				 "MUNICIPALITY" : "Woodstock", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "360 Albert St", 
        				 "POSTALCODE" : "N4S2L4",
        				 "PHONE" : "5195391131",
        				 "FAX" : "5195391193",
        				 "WEB" : "http://www.tvdsb.ca/Southside.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Southside,Woodstock",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "2.8", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "2199/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3662,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.5825653,43.7447319]},
        		"properties" : { 
        				 "NAME" : "St Andrew", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2533 Kipling Ave", 
        				 "POSTALCODE" : "M9V3A8",
        				 "PHONE" : "4163935295",
        				 "FAX" : "4162297052",
        				 "WEB" : "http://www.tcdsb.org/schools/standrew.asp",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "St Andrew,Toronto",
        				 "Rating2011_12" : "2.9", 
        				 "Rating_in_the_most_recent_five_years" : "3.2", 
        				 "Rank2011_12" : "2559/2714",
        				 "Rank_in_the_most_recent_five_years" : "2164/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3722,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.5250168,43.7682419]},
        		"properties" : { 
        				 "NAME" : "St Augustine", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "98 Shoreham Dr", 
        				 "POSTALCODE" : "M3N1S9",
        				 "PHONE" : "4163935328",
        				 "FAX" : "4163935156",
        				 "WEB" : "http://www.tcdsb.org/schools/staugustine.asp",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "St Augustine,Toronto",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "3.6", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "2124/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3804,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.5180969,43.7625999]},
        		"properties" : { 
        				 "NAME" : "St Charles Garnier", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "20 Stong Crt", 
        				 "POSTALCODE" : "M3N2X9",
        				 "PHONE" : "4163935363",
        				 "FAX" : "4163935174",
        				 "WEB" : "http://www.tcdsb.org/schools/stcharlesgarnier.asp",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "St Charles Garnier,Toronto",
        				 "Rating2011_12" : "2.7", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2583/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4232,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.6017685,42.6056557]},
        		"properties" : { 
        				 "NAME" : "St Mary's", 
        				 "MUNICIPALITY" : "West Lorne", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 119", 
        				 "STREET" : "128 William St", 
        				 "POSTALCODE" : "N0L2P0",
        				 "PHONE" : "5196602788",
        				 "FAX" : "",
        				 "WEB" : "http://www.ldcsb.on.ca/schools/mawl",
        				 "BOARD_NAME" : "London District Board",
        				 "ProvincalName" : "St Mary's,West Lorne",
        				 "Rating2011_12" : "2.8", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2569/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4348,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.8558807,43.2527199]},
        		"properties" : { 
        				 "NAME" : "St Patrick's", 
        				 "MUNICIPALITY" : "Hamilton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "20 East Ave S", 
        				 "POSTALCODE" : "L8N3X1",
        				 "PHONE" : "9055291069",
        				 "FAX" : "9055292201",
        				 "WEB" : "http://www.hwcdsb.ca/stpatrick/",
        				 "BOARD_NAME" : "Hamilton-Wentworth CDSB",
        				 "ProvincalName" : "St Patrick's,Hamilton",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "2.9", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "2189/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4377,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.3309937,48.4834633]},
        		"properties" : { 
        				 "NAME" : "St Paul", 
        				 "MUNICIPALITY" : "Timmins", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "387 Balsam St N", 
        				 "POSTALCODE" : "P4N6H5",
        				 "PHONE" : "7052645620",
        				 "FAX" : "7052675121",
        				 "WEB" : "http://www.ncdsb.on.ca/schools/school.php?id=12&page=profile",
        				 "BOARD_NAME" : "Northeastern CDSB",
        				 "ProvincalName" : "St Paul,Timmins",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "1.2", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "2263/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4387,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.579277,44.0999489]},
        		"properties" : { 
        				 "NAME" : "St Peter", 
        				 "MUNICIPALITY" : "Trenton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "101 Queen St", 
        				 "POSTALCODE" : "K8V4Y2",
        				 "PHONE" : "6133926577",
        				 "FAX" : "6133923191",
        				 "WEB" : "http://schools.alcdsb.on.ca/pett/default.aspx",
        				 "BOARD_NAME" : "Algonquin and Lakeshore CDSB",
        				 "ProvincalName" : "St Peter,Trenton",
        				 "Rating2011_12" : "2.7", 
        				 "Rating_in_the_most_recent_five_years" : "3.8", 
        				 "Rank2011_12" : "2583/2714",
        				 "Rank_in_the_most_recent_five_years" : "2083/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4402,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.5101395,43.7188988]},
        		"properties" : { 
        				 "NAME" : "St Philip Neri", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "20 Beverly Hills Dr", 
        				 "POSTALCODE" : "M3L1A1",
        				 "PHONE" : "4163935254",
        				 "FAX" : "4163935245",
        				 "WEB" : "http://www.tcdsb.org/schools/stphilipneri.asp",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "St Philip Neri,Toronto",
        				 "Rating2011_12" : "2.9", 
        				 "Rating_in_the_most_recent_five_years" : "3.9", 
        				 "Rank2011_12" : "2559/2714",
        				 "Rank_in_the_most_recent_five_years" : "2059/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4438,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.1673965,42.9956017]},
        		"properties" : { 
        				 "NAME" : "St Robert", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1958 Duluth Cres", 
        				 "POSTALCODE" : "N5V1H7",
        				 "PHONE" : "5196754430",
        				 "FAX" : "5196754430",
        				 "WEB" : "http://www.ldcsb.on.ca/schools/robe/",
        				 "BOARD_NAME" : "London District Board",
        				 "ProvincalName" : "St Robert,London",
        				 "Rating2011_12" : "2.8", 
        				 "Rating_in_the_most_recent_five_years" : "3.3", 
        				 "Rank2011_12" : "2569/2714",
        				 "Rank_in_the_most_recent_five_years" : "2156/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1006,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.1684494,48.4931145]},
        		"properties" : { 
        				 "NAME" : "St-Jude", 
        				 "MUNICIPALITY" : "Porcupine", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "French", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "255 rue Dixon", 
        				 "POSTALCODE" : "P0N1C0",
        				 "PHONE" : "7052352411",
        				 "FAX" : "7052355508",
        				 "WEB" : "http://www.cscdgr.on.ca",
        				 "BOARD_NAME" : "CSDC des Grandes Rivières",
        				 "ProvincalName" : "St-Jude,Porcupine",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "3.7", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "2105/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4560,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3660965,44.3024635]},
        		"properties" : { 
        				 "NAME" : "Sutton", 
        				 "MUNICIPALITY" : "Sutton West", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 190", 
        				 "STREET" : "5147 Baseline Rd", 
        				 "POSTALCODE" : "L0E1R0",
        				 "PHONE" : "9057223782",
        				 "FAX" : "9057224030",
        				 "WEB" : "http://www.sutton.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "Sutton,Sutton West",
        				 "Rating2011_12" : "2.7", 
        				 "Rating_in_the_most_recent_five_years" : "3.8", 
        				 "Rank2011_12" : "2583/2714",
        				 "Rank_in_the_most_recent_five_years" : "2083/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4580,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.7874908,43.3467903]},
        		"properties" : { 
        				 "NAME" : "Tecumseh", 
        				 "MUNICIPALITY" : "Burlington", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "3141 Woodward Ave", 
        				 "POSTALCODE" : "L7N2M3",
        				 "PHONE" : "9056398330",
        				 "FAX" : "9056393392",
        				 "WEB" : "http://tec.hdsb.ca",
        				 "BOARD_NAME" : "Halton DSB",
        				 "ProvincalName" : "Tecumseh,Burlington",
        				 "Rating2011_12" : "3", 
        				 "Rating_in_the_most_recent_five_years" : "2.4", 
        				 "Rank2011_12" : "2543/2714",
        				 "Rank_in_the_most_recent_five_years" : "2230/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4611,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.9573059,44.2490921]},
        		"properties" : { 
        				 "NAME" : "The Prince Charles", 
        				 "MUNICIPALITY" : "Napanee", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "75 Graham St W", 
        				 "POSTALCODE" : "K7R2J9",
        				 "PHONE" : "6133542121",
        				 "FAX" : "6133546664",
        				 "WEB" : "http://theprincecharles.limestone.on.ca/",
        				 "BOARD_NAME" : "Limestone DSB",
        				 "ProvincalName" : "The Prince Charles,Napanee",
        				 "Rating2011_12" : "2.5", 
        				 "Rating_in_the_most_recent_five_years" : "3.9", 
        				 "Rank2011_12" : "2606/2714",
        				 "Rank_in_the_most_recent_five_years" : "2059/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4658,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [0,0]},
        		"properties" : { 
        				 "NAME" : "Trafalgar", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "919 Trafalgar St", 
        				 "POSTALCODE" : "N5Z1G3",
        				 "PHONE" : "5194528610",
        				 "FAX" : "5194528619",
        				 "WEB" : "http://www.tvdsb.ca/Trafalgar.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Trafalgar,London",
        				 "Rating2011_12" : "2.4", 
        				 "Rating_in_the_most_recent_five_years" : "1.7", 
        				 "Rank2011_12" : "2612/2714",
        				 "Rank_in_the_most_recent_five_years" : "2250/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4742,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.5738831,44.1224709]},
        		"properties" : { 
        				 "NAME" : "V P Carswell", 
        				 "MUNICIPALITY" : "Trenton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "4 Seneca Rd", 
        				 "POSTALCODE" : "K8V2E9",
        				 "PHONE" : "6133928845",
        				 "FAX" : "6133924044",
        				 "WEB" : "http://edu.hpedsb.on.ca/vpcar/",
        				 "BOARD_NAME" : "Hastings & Prince Edward DSB",
        				 "ProvincalName" : "V P Carswell,Trenton",
        				 "Rating2011_12" : "2.7", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2583/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4708,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.7065353,44.6062584]},
        		"properties" : { 
        				 "NAME" : "Vanier", 
        				 "MUNICIPALITY" : "Brockville", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "40 Vanier Drive", 
        				 "POSTALCODE" : "K6V3J5",
        				 "PHONE" : "6133428081",
        				 "FAX" : "6134980586",
        				 "WEB" : "http://vanier.ucdsb.on.ca",
        				 "BOARD_NAME" : "Upper Canada DSB",
        				 "ProvincalName" : "Vanier,Brockville",
        				 "Rating2011_12" : "2.5", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2606/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4937,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2866592,42.9665489]},
        		"properties" : { 
        				 "NAME" : "Woodland Heights", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "474 Springbank Dr", 
        				 "POSTALCODE" : "N6J1G8",
        				 "PHONE" : "5194528710",
        				 "FAX" : "5194528719",
        				 "WEB" : "http://www.tvdsb.ca/WoodlandHeights.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Woodland Heights,London",
        				 "Rating2011_12" : "2.6", 
        				 "Rating_in_the_most_recent_five_years" : "4.8", 
        				 "Rank2011_12" : "2594/2714",
        				 "Rank_in_the_most_recent_five_years" : "1806/2268",
        				 "popupContent": "Put more data here" }}
             ]
    };
    