 var schools9 = { 
    "type" : "FeatureCollection",
        "features" : [
             { "type" : "Feature",
        "id" : 61,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-78.7447968,44.3586769]},
        		"properties" : { 
        				 "NAME" : "Alexandra", 
        				 "MUNICIPALITY" : "Lindsay", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "65 Sussex St N", 
        				 "POSTALCODE" : "K9V4H9",
        				 "PHONE" : "7053243313",
        				 "FAX" : "7053242262",
        				 "WEB" : "http://aps.tldsb.on.ca/",
        				 "BOARD_NAME" : "Trillium Lakelands DSB",
        				 "ProvincalName" : "Alexandra,Lindsay",
        				 "Rating2011_12" : "9", 
        				 "Rating_in_the_most_recent_five_years" : "9.4", 
        				 "Rank2011_12" : "78/2714",
        				 "Rank_in_the_most_recent_five_years" : "21/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 133,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.7266388,44.3555298]},
        		"properties" : { 
        				 "NAME" : "Ardagh Bluffs", 
        				 "MUNICIPALITY" : "Barrie", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "159 Summerset Drive", 
        				 "POSTALCODE" : "L4N6H2",
        				 "PHONE" : "",
        				 "FAX" : "",
        				 "WEB" : "http://agh.scdsb.on.ca",
        				 "BOARD_NAME" : "Simcoe County DSB",
        				 "ProvincalName" : "Ardagh Bluffs,Barrie",
        				 "Rating2011_12" : "9.2", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "57/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 217,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3925323,43.8105087]},
        		"properties" : { 
        				 "NAME" : "Bayview Glen", 
        				 "MUNICIPALITY" : "Thornhill", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "42 Limcombe Dr", 
        				 "POSTALCODE" : "L3T2V5",
        				 "PHONE" : "9058892448",
        				 "FAX" : "9058892578",
        				 "WEB" : "http://www.bayviewglen.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "Bayview Glen,Thornhill",
        				 "Rating2011_12" : "9.4", 
        				 "Rating_in_the_most_recent_five_years" : "9.6", 
        				 "Rank2011_12" : "41/2714",
        				 "Rank_in_the_most_recent_five_years" : "13/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 342,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.389473,43.7199287]},
        		"properties" : { 
        				 "NAME" : "Blythwood", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2 Strathgowan Cres", 
        				 "POSTALCODE" : "M4N2Z5",
        				 "PHONE" : "4163939105",
        				 "FAX" : "4163939107",
        				 "WEB" : "http://www.tdsb.on.ca/schools/index.asp?schno=5297",
        				 "BOARD_NAME" : "Toronto DSB",
        				 "ProvincalName" : "Blythwood,Toronto",
        				 "Rating2011_12" : "9.8", 
        				 "Rating_in_the_most_recent_five_years" : "9.5", 
        				 "Rank2011_12" : "20/2714",
        				 "Rank_in_the_most_recent_five_years" : "18/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 440,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3554382,43.864769]},
        		"properties" : { 
        				 "NAME" : "Buttonville", 
        				 "MUNICIPALITY" : "Markham", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "141 John Button Blvd", 
        				 "POSTALCODE" : "L3R9C2",
        				 "PHONE" : "9055139880",
        				 "FAX" : "9055131755",
        				 "WEB" : "http://www.buttonville.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "Buttonville,Markham",
        				 "Rating2011_12" : "9.1", 
        				 "Rating_in_the_most_recent_five_years" : "8.4", 
        				 "Rank2011_12" : "67/2714",
        				 "Rank_in_the_most_recent_five_years" : "104/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 509,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3038406,43.8975487]},
        		"properties" : { 
        				 "NAME" : "Castlemore", 
        				 "MUNICIPALITY" : "Markham", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "256 Ridgecrest Rd", 
        				 "POSTALCODE" : "L6C2R5",
        				 "PHONE" : "9058871543",
        				 "FAX" : "9058873849",
        				 "WEB" : "http://www.castlemore.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "Castlemore,Markham",
        				 "Rating2011_12" : "9.2", 
        				 "Rating_in_the_most_recent_five_years" : "8.7", 
        				 "Rank2011_12" : "57/2714",
        				 "Rank_in_the_most_recent_five_years" : "63/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 701,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3437271,43.8644409]},
        		"properties" : { 
        				 "NAME" : "Coledale", 
        				 "MUNICIPALITY" : "Markham", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "60 Coledale Rd", 
        				 "POSTALCODE" : "L3R7W8",
        				 "PHONE" : "9059400123",
        				 "FAX" : "9059409760",
        				 "WEB" : "http://www.coledale.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "Coledale,Markham",
        				 "Rating2011_12" : "9", 
        				 "Rating_in_the_most_recent_five_years" : "9.1", 
        				 "Rank2011_12" : "78/2714",
        				 "Rank_in_the_most_recent_five_years" : "33/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 829,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3641891,43.7458382]},
        		"properties" : { 
        				 "NAME" : "Denlow", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "50 Denlow Blvd", 
        				 "POSTALCODE" : "M3B1P7",
        				 "PHONE" : "4163952300",
        				 "FAX" : "4163952302",
        				 "WEB" : "http://www.tdsb.on.ca/SchoolWeb/_site/viewitem.asp?siteid=10432&pageid=20328&menuid=23453",
        				 "BOARD_NAME" : "Toronto DSB",
        				 "ProvincalName" : "Denlow,Toronto",
        				 "Rating2011_12" : "9.6", 
        				 "Rating_in_the_most_recent_five_years" : "9.7", 
        				 "Rank2011_12" : "31/2714",
        				 "Rank_in_the_most_recent_five_years" : "10/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1405,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.6579132,43.4681206]},
        		"properties" : { 
        				 "NAME" : "E J James", 
        				 "MUNICIPALITY" : "Oakville", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "08-Jan", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "338 Cairncroft Rd", 
        				 "POSTALCODE" : "L6J4M6",
        				 "PHONE" : "9058452015",
        				 "FAX" : "",
        				 "WEB" : "http://ejj.hdsb.ca",
        				 "BOARD_NAME" : "Halton DSB",
        				 "ProvincalName" : "E J James,Oakville",
        				 "Rating2011_12" : "9.1", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "67/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1350,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.2560806,43.5658989]},
        		"properties" : { 
        				 "NAME" : "Edward Johnson", 
        				 "MUNICIPALITY" : "Guelph", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "397 Stevenson St N", 
        				 "POSTALCODE" : "N1E5C1",
        				 "PHONE" : "5197637374",
        				 "FAX" : "5197636344",
        				 "WEB" : "http://www.ugdsb.on.ca/johnson",
        				 "BOARD_NAME" : "Upper Grand DSB",
        				 "ProvincalName" : "Edward Johnson,Guelph",
        				 "Rating2011_12" : "10", 
        				 "Rating_in_the_most_recent_five_years" : "9", 
        				 "Rank2011_12" : "1/2714",
        				 "Rank_in_the_most_recent_five_years" : "40/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1411,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.5399017,44.3193817]},
        		"properties" : { 
        				 "NAME" : "Elginburg", 
        				 "MUNICIPALITY" : "Elginburg", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2100 Unity Rd", 
        				 "POSTALCODE" : "K0H1M0",
        				 "PHONE" : "6135428387",
        				 "FAX" : "6135422530",
        				 "WEB" : "http://elginburg.limestone.on.ca/",
        				 "BOARD_NAME" : "Limestone DSB",
        				 "ProvincalName" : "Elginburg,Elginburg",
        				 "Rating2011_12" : "9.7", 
        				 "Rating_in_the_most_recent_five_years" : "8.1", 
        				 "Rank2011_12" : "25/2714",
        				 "Rank_in_the_most_recent_five_years" : "176/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1032,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.6730194,45.3636208]},
        		"properties" : { 
        				 "NAME" : "Georges-ƒtienne-Cartier", 
        				 "MUNICIPALITY" : "Ottawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "French", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "880 prom. Thorndale", 
        				 "POSTALCODE" : "K1V6Y3",
        				 "PHONE" : "6137316007",
        				 "FAX" : "6137316016",
        				 "WEB" : "http://www.george-etienne-cartier.ecolecatholique.ca",
        				 "BOARD_NAME" : "CSDC du Centre-Est de l'Ontario",
        				 "ProvincalName" : "Georges-ƒtienne-Cartier,Ottawa",
        				 "Rating2011_12" : "9.2", 
        				 "Rating_in_the_most_recent_five_years" : "7.6", 
        				 "Rank2011_12" : "57/2714",
        				 "Rank_in_the_most_recent_five_years" : "337/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1753,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.2819519,43.1950111]},
        		"properties" : { 
        				 "NAME" : "Gracefield", 
        				 "MUNICIPALITY" : "St Catharines", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "117 Bayview Dr", 
        				 "POSTALCODE" : "L2N4Z7",
        				 "PHONE" : "9059341411",
        				 "FAX" : "9059341876",
        				 "WEB" : "http://www.dsbn.edu.on.ca/Schools/Gracefield/",
        				 "BOARD_NAME" : "DSB Niagara",
        				 "ProvincalName" : "Gracefield,St Catharines",
        				 "Rating2011_12" : "9.4", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "41/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1790,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-82.2160568,42.4205093]},
        		"properties" : { 
        				 "NAME" : "Gregory Drive", 
        				 "MUNICIPALITY" : "Chatham", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "180 Gregory Dr W", 
        				 "POSTALCODE" : "N7L2L4",
        				 "PHONE" : "5193526856",
        				 "FAX" : "5193526897",
        				 "WEB" : "http://gregorydrive.lkdsb.net/",
        				 "BOARD_NAME" : "Lambton Kent DSB",
        				 "ProvincalName" : "Gregory Drive,Chatham",
        				 "Rating2011_12" : "9.6", 
        				 "Rating_in_the_most_recent_five_years" : "8.8", 
        				 "Rank2011_12" : "31/2714",
        				 "Rank_in_the_most_recent_five_years" : "53/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1851,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4090576,43.8050613]},
        		"properties" : { 
        				 "NAME" : "Henderson Avenue", 
        				 "MUNICIPALITY" : "Thornhill", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "66 Henderson Ave", 
        				 "POSTALCODE" : "L3T2K7",
        				 "PHONE" : "9058893132",
        				 "FAX" : "9058899953",
        				 "WEB" : "http://www.hendersonavenue.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "Henderson Avenue,Thornhill",
        				 "Rating2011_12" : "9.3", 
        				 "Rating_in_the_most_recent_five_years" : "8.9", 
        				 "Rank2011_12" : "52/2714",
        				 "Rank_in_the_most_recent_five_years" : "47/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1907,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3506775,43.7994118]},
        		"properties" : { 
        				 "NAME" : "Hillmount", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "245 McNicoll Ave", 
        				 "POSTALCODE" : "M2H2C6",
        				 "PHONE" : "4163952550",
        				 "FAX" : "4163954483",
        				 "WEB" : "http://schools.tdsb.on.ca/hillmount/",
        				 "BOARD_NAME" : "Toronto DSB",
        				 "ProvincalName" : "Hillmount,Toronto",
        				 "Rating2011_12" : "10", 
        				 "Rating_in_the_most_recent_five_years" : "10", 
        				 "Rank2011_12" : "1/2714",
        				 "Rank_in_the_most_recent_five_years" : "1/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1932,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-83.0151672,42.2411156]},
        		"properties" : { 
        				 "NAME" : "Holy Cross", 
        				 "MUNICIPALITY" : "Lasalle", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2555 Sandwich W Pkwy", 
        				 "POSTALCODE" : "N9H2P7",
        				 "PHONE" : "5199726050",
        				 "FAX" : "5199722598",
        				 "WEB" : "http://www.wecdsb.on.ca/ourschools.asp?OANum=107",
        				 "BOARD_NAME" : "Windsor-Essex CDSB",
        				 "ProvincalName" : "Holy Cross,Lasalle",
        				 "Rating2011_12" : "9", 
        				 "Rating_in_the_most_recent_five_years" : "7.7", 
        				 "Rank2011_12" : "78/2714",
        				 "Rank_in_the_most_recent_five_years" : "300/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2161,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.1028137,43.116478]},
        		"properties" : { 
        				 "NAME" : "John Marshall", 
        				 "MUNICIPALITY" : "Niagara Falls", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "3910 St James Ave", 
        				 "POSTALCODE" : "L2J2R3",
        				 "PHONE" : "9053583711",
        				 "FAX" : "9053588482",
        				 "WEB" : "http://www.dsbn.edu.on.ca/Schools/jmarshall/",
        				 "BOARD_NAME" : "DSB Niagara",
        				 "ProvincalName" : "John Marshall,Niagara Falls",
        				 "Rating2011_12" : "9.2", 
        				 "Rating_in_the_most_recent_five_years" : "8.3", 
        				 "Rank2011_12" : "57/2714",
        				 "Rank_in_the_most_recent_five_years" : "127/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2162,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.2874832,43.9018097]},
        		"properties" : { 
        				 "NAME" : "John McCrae", 
        				 "MUNICIPALITY" : "Markham", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "565 Fred McLaren Blvd", 
        				 "POSTALCODE" : "L6E1N7",
        				 "PHONE" : "9052949122",
        				 "FAX" : "9052948196",
        				 "WEB" : "http://www.johnmccrae.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "John McCrae,Markham",
        				 "Rating2011_12" : "9.2", 
        				 "Rating_in_the_most_recent_five_years" : "8.6", 
        				 "Rank2011_12" : "57/2714",
        				 "Rank_in_the_most_recent_five_years" : "72/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2174,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4088211,43.7183304]},
        		"properties" : { 
        				 "NAME" : "John Ross Robertson", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "130 Glengrove Ave W", 
        				 "POSTALCODE" : "M4R1P2",
        				 "PHONE" : "4163939400",
        				 "FAX" : "4163939404",
        				 "WEB" : "http://www.tdsb.on.ca/SchoolWeb/_site/viewitem.asp?siteid=10064&pageid=7629&menuid=8715",
        				 "BOARD_NAME" : "Toronto DSB",
        				 "ProvincalName" : "John Ross Robertson,Toronto",
        				 "Rating2011_12" : "9.6", 
        				 "Rating_in_the_most_recent_five_years" : "9.6", 
        				 "Rank2011_12" : "31/2714",
        				 "Rank_in_the_most_recent_five_years" : "13/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2185,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.3632202,45.4298897]},
        		"properties" : { 
        				 "NAME" : "John XXIII", 
        				 "MUNICIPALITY" : "Arnprior", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "75 Edey St", 
        				 "POSTALCODE" : "K7S1B9",
        				 "PHONE" : "6136232828",
        				 "FAX" : "6136230785",
        				 "WEB" : "http://www.rccdsb.edu.on.ca/john23/",
        				 "BOARD_NAME" : "Renfrew County CDSB",
        				 "ProvincalName" : "John XXIII,Arnprior",
        				 "Rating2011_12" : "10", 
        				 "Rating_in_the_most_recent_five_years" : "9.7", 
        				 "Rank2011_12" : "1/2714",
        				 "Rank_in_the_most_recent_five_years" : "10/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2196,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.5659866,43.659481]},
        		"properties" : { 
        				 "NAME" : "Josyf Cardinal Slipyj", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "35 West Deane Park Dr", 
        				 "POSTALCODE" : "M9B2R5",
        				 "PHONE" : "4163935413",
        				 "FAX" : "4163976044",
        				 "WEB" : "http://www.tcdsb.org/josyfcardinalslipyj/",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "Josyf Cardinal Slipyj,Toronto",
        				 "Rating2011_12" : "9.2", 
        				 "Rating_in_the_most_recent_five_years" : "8.6", 
        				 "Rank2011_12" : "57/2714",
        				 "Rank_in_the_most_recent_five_years" : "72/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2215,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.8899612,45.3101387]},
        		"properties" : { 
        				 "NAME" : "Katimavik", 
        				 "MUNICIPALITY" : "Kanata", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "64 Chimo Dr", 
        				 "POSTALCODE" : "K2L1Y9",
        				 "PHONE" : "6135925462",
        				 "FAX" : "6135926987",
        				 "WEB" : "http://www.katimavikes.ocdsb.ca/",
        				 "BOARD_NAME" : "Ottawa-Carleton DSB",
        				 "ProvincalName" : "Katimavik,Kanata",
        				 "Rating2011_12" : "9", 
        				 "Rating_in_the_most_recent_five_years" : "9.2", 
        				 "Rank2011_12" : "78/2714",
        				 "Rank_in_the_most_recent_five_years" : "28/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2229,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.5976257,43.5576744]},
        		"properties" : { 
        				 "NAME" : "Kenollie", 
        				 "MUNICIPALITY" : "Mississauga", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1376 Glenwood Dr", 
        				 "POSTALCODE" : "L5G2X1",
        				 "PHONE" : "9052788991",
        				 "FAX" : "9052781595",
        				 "WEB" : "http://schools.peelschools.org/1279/Pages/default.aspx",
        				 "BOARD_NAME" : "Peel DSB",
        				 "ProvincalName" : "Kenollie,Mississauga",
        				 "Rating2011_12" : "9.2", 
        				 "Rating_in_the_most_recent_five_years" : "9.3", 
        				 "Rank2011_12" : "57/2714",
        				 "Rank_in_the_most_recent_five_years" : "24/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2344,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.5756912,43.4690704]},
        		"properties" : { 
        				 "NAME" : "Laurelwood", 
        				 "MUNICIPALITY" : "Waterloo", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "460 Brentcliffe Dr", 
        				 "POSTALCODE" : "N2T2R5",
        				 "PHONE" : "5198849999",
        				 "FAX" : "5198849502",
        				 "WEB" : "http://lrw.wrdsb.on.ca/",
        				 "BOARD_NAME" : "Waterloo Region DSB",
        				 "ProvincalName" : "Laurelwood,Waterloo",
        				 "Rating2011_12" : "9.7", 
        				 "Rating_in_the_most_recent_five_years" : "8.6", 
        				 "Rank2011_12" : "25/2714",
        				 "Rank_in_the_most_recent_five_years" : "72/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2455,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4560623,43.9242096]},
        		"properties" : { 
        				 "NAME" : "MacLeod's Landing", 
        				 "MUNICIPALITY" : "Richmond Hill", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "195 Silver Maple Rd", 
        				 "POSTALCODE" : "L4E4Z1",
        				 "PHONE" : "9053987945",
        				 "FAX" : "9053980842",
        				 "WEB" : "http://www.macleodslanding.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "MacLeod's Landing,Richmond Hill",
        				 "Rating2011_12" : "9.4", 
        				 "Rating_in_the_most_recent_five_years" : "8.2", 
        				 "Rank2011_12" : "41/2714",
        				 "Rank_in_the_most_recent_five_years" : "148/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2480,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.6503372,43.473629]},
        		"properties" : { 
        				 "NAME" : "Maple Grove", 
        				 "MUNICIPALITY" : "Oakville", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "288 Maple Grove Dr", 
        				 "POSTALCODE" : "L6J4V5",
        				 "PHONE" : "9058449322",
        				 "FAX" : "9058447100",
        				 "WEB" : "http://mag.hdsb.ca/",
        				 "BOARD_NAME" : "Halton DSB",
        				 "ProvincalName" : "Maple Grove,Oakville",
        				 "Rating2011_12" : "9.2", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "57/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2879,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3922195,43.6586304]},
        		"properties" : { 
        				 "NAME" : "Orde Street", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "18 Orde St", 
        				 "POSTALCODE" : "M5T1N7",
        				 "PHONE" : "4163931900",
        				 "FAX" : "4163930864",
        				 "WEB" : "http://www.tdsb.on.ca/SchoolWeb/_site/viewitem.asp?siteid=10340&pageid=16506&menuid=18775",
        				 "BOARD_NAME" : "Toronto DSB",
        				 "ProvincalName" : "Orde Street,Toronto",
        				 "Rating2011_12" : "9.2", 
        				 "Rating_in_the_most_recent_five_years" : "8.2", 
        				 "Rank2011_12" : "57/2714",
        				 "Rank_in_the_most_recent_five_years" : "148/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2920,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.7111816,43.5916786]},
        		"properties" : { 
        				 "NAME" : "Our Lady of Good Voyage", 
        				 "MUNICIPALITY" : "Mississauga", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "5850 River Grove Ave", 
        				 "POSTALCODE" : "L5M4W2",
        				 "PHONE" : "9055678422",
        				 "FAX" : "9055677832",
        				 "WEB" : "http://www.dpcdsb.org/OLGDV",
        				 "BOARD_NAME" : "Dufferin-Peel CDSB",
        				 "ProvincalName" : "Our Lady of Good Voyage,Mississauga",
        				 "Rating2011_12" : "9.1", 
        				 "Rating_in_the_most_recent_five_years" : "8.2", 
        				 "Rank2011_12" : "67/2714",
        				 "Rank_in_the_most_recent_five_years" : "148/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2929,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.5302277,43.4590607]},
        		"properties" : { 
        				 "NAME" : "Our Lady of Lourdes", 
        				 "MUNICIPALITY" : "Waterloo", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "55 Roslin Ave S", 
        				 "POSTALCODE" : "N2L6N5",
        				 "PHONE" : "5198864810",
        				 "FAX" : "5198864812",
        				 "WEB" : "http://lourdes.wcdsb.ca",
        				 "BOARD_NAME" : "Waterloo CDSB",
        				 "ProvincalName" : "Our Lady of Lourdes,Waterloo",
        				 "Rating2011_12" : "9.1", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "67/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2938,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.4274063,42.914257]},
        		"properties" : { 
        				 "NAME" : "Our Lady of Lourdes", 
        				 "MUNICIPALITY" : "Delaware", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2436 Gideon Dr", 
        				 "POSTALCODE" : "N0L1E0",
        				 "PHONE" : "5196602775",
        				 "FAX" : "",
        				 "WEB" : "http://www.ldcsb.on.ca/schools/oll/index.htm",
        				 "BOARD_NAME" : "London District Board",
        				 "ProvincalName" : "Our Lady of Lourdes,Delaware",
        				 "Rating2011_12" : "9.5", 
        				 "Rating_in_the_most_recent_five_years" : "7.5", 
        				 "Rank2011_12" : "37/2714",
        				 "Rank_in_the_most_recent_five_years" : "372/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2959,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3835526,43.6876106]},
        		"properties" : { 
        				 "NAME" : "Our Lady of Perpetual Help", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1 1/2 Garfield Ave", 
        				 "POSTALCODE" : "M4T1E6",
        				 "PHONE" : "4163935239",
        				 "FAX" : "4163935818",
        				 "WEB" : "http://www.tcdsb.org/schools/ourladyofperpetualhelp.asp",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "Our Lady of Perpetual Help,Toronto",
        				 "Rating2011_12" : "10", 
        				 "Rating_in_the_most_recent_five_years" : "9.8", 
        				 "Rank2011_12" : "1/2714",
        				 "Rank_in_the_most_recent_five_years" : "7/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3078,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.2520218,43.2038307]},
        		"properties" : { 
        				 "NAME" : "Pine Grove", 
        				 "MUNICIPALITY" : "St Catharines", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "690 Lake St", 
        				 "POSTALCODE" : "L2N4J5",
        				 "PHONE" : "9059351901",
        				 "FAX" : "9059350173",
        				 "WEB" : "http://www.dsbn.edu.on.ca/Schools/Pinegrove/",
        				 "BOARD_NAME" : "DSB Niagara",
        				 "ProvincalName" : "Pine Grove,St Catharines",
        				 "Rating2011_12" : "10", 
        				 "Rating_in_the_most_recent_five_years" : "9.6", 
        				 "Rank2011_12" : "1/2714",
        				 "Rank_in_the_most_recent_five_years" : "13/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3153,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.2789001,43.8253899]},
        		"properties" : { 
        				 "NAME" : "Prince of Peace", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "255 Alton Towers Cir", 
        				 "POSTALCODE" : "M1V4E7",
        				 "PHONE" : "4163935416",
        				 "FAX" : "4163976005",
        				 "WEB" : "http://www.tcdsb.org/schools/princeofpeace.asp",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "Prince of Peace,Toronto",
        				 "Rating2011_12" : "9.7", 
        				 "Rating_in_the_most_recent_five_years" : "9.6", 
        				 "Rank2011_12" : "25/2714",
        				 "Rank_in_the_most_recent_five_years" : "13/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3306,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.9932327,46.44981]},
        		"properties" : { 
        				 "NAME" : "R L Beattie", 
        				 "MUNICIPALITY" : "Sudbury", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "102 Loach's Rd", 
        				 "POSTALCODE" : "P3E2P7",
        				 "PHONE" : "7055227178",
        				 "FAX" : "7055226197",
        				 "WEB" : "http://www.rainbowschools.ca/elementary/rl_beattie/index.php",
        				 "BOARD_NAME" : "Rainbow DSB",
        				 "ProvincalName" : "R L Beattie,Sudbury",
        				 "Rating2011_12" : "10", 
        				 "Rating_in_the_most_recent_five_years" : "9.1", 
        				 "Rank2011_12" : "1/2714",
        				 "Rank_in_the_most_recent_five_years" : "33/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3263,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4134903,43.8838692]},
        		"properties" : { 
        				 "NAME" : "Richmond Rose", 
        				 "MUNICIPALITY" : "Richmond Hill", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "160 Frank Endean Rd", 
        				 "POSTALCODE" : "L4S1S7",
        				 "PHONE" : "9057374311",
        				 "FAX" : "9057373820",
        				 "WEB" : "http://www.richmondrose.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "Richmond Rose,Richmond Hill",
        				 "Rating2011_12" : "9", 
        				 "Rating_in_the_most_recent_five_years" : "8.6", 
        				 "Rank2011_12" : "78/2714",
        				 "Rank_in_the_most_recent_five_years" : "72/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3357,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3816528,43.6776619]},
        		"properties" : { 
        				 "NAME" : "Rosedale", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "22 South Dr", 
        				 "POSTALCODE" : "M4W1R1",
        				 "PHONE" : "4163931330",
        				 "FAX" : "4163931332",
        				 "WEB" : "http://www.tdsb.on.ca/MOSS/asp_apps/school_landing_page/index.asp?schno=5271",
        				 "BOARD_NAME" : "Toronto DSB",
        				 "ProvincalName" : "Rosedale,Toronto",
        				 "Rating2011_12" : "9.3", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "52/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3451,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.2826767,43.8973312]},
        		"properties" : { 
        				 "NAME" : "San Lorenzo Ruiz", 
        				 "MUNICIPALITY" : "Markham", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "840 Bur Oak Ave", 
        				 "POSTALCODE" : "L6E0E1",
        				 "PHONE" : "9052022430",
        				 "FAX" : "9052947886",
        				 "WEB" : "http://slr.ycdsb.ca/",
        				 "BOARD_NAME" : "York CDSB",
        				 "ProvincalName" : "San Lorenzo Ruiz,Markham",
        				 "Rating2011_12" : "9.1", 
        				 "Rating_in_the_most_recent_five_years" : "8.9", 
        				 "Rank2011_12" : "67/2714",
        				 "Rank_in_the_most_recent_five_years" : "47/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3806,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.5672684,44.0933075]},
        		"properties" : { 
        				 "NAME" : "St Charles", 
        				 "MUNICIPALITY" : "Bradford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 719", 
        				 "STREET" : "691 Simcoe Rd", 
        				 "POSTALCODE" : "L3Z2B2",
        				 "PHONE" : "9057756762",
        				 "FAX" : "9057751792",
        				 "WEB" : "http://sch.schools.smcdsb.on.ca",
        				 "BOARD_NAME" : "Simcoe Muskoka CDSB",
        				 "ProvincalName" : "St Charles,Bradford",
        				 "Rating2011_12" : "9.4", 
        				 "Rating_in_the_most_recent_five_years" : "8.4", 
        				 "Rank2011_12" : "41/2714",
        				 "Rank_in_the_most_recent_five_years" : "104/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3841,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.5219269,43.6846619]},
        		"properties" : { 
        				 "NAME" : "St Demetrius", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "125 La Rose Ave", 
        				 "POSTALCODE" : "M9P1A6",
        				 "PHONE" : "4163935384",
        				 "FAX" : "4163935087",
        				 "WEB" : "http://www.tcdsb.org/schools/stdemetrius.asp",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "St Demetrius,Toronto",
        				 "Rating2011_12" : "9", 
        				 "Rating_in_the_most_recent_five_years" : "9", 
        				 "Rank2011_12" : "78/2714",
        				 "Rank_in_the_most_recent_five_years" : "40/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3853,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.6880417,43.5789719]},
        		"properties" : { 
        				 "NAME" : "St Dunstan", 
        				 "MUNICIPALITY" : "Mississauga", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1525 Cuthbert Ave", 
        				 "POSTALCODE" : "L5M3R6",
        				 "PHONE" : "9055675050",
        				 "FAX" : "9055670288",
        				 "WEB" : "http://www.dpcdsb.org/DUNST",
        				 "BOARD_NAME" : "Dufferin-Peel CDSB",
        				 "ProvincalName" : "St Dunstan,Mississauga",
        				 "Rating2011_12" : "9.1", 
        				 "Rating_in_the_most_recent_five_years" : "8.6", 
        				 "Rank2011_12" : "67/2714",
        				 "Rank_in_the_most_recent_five_years" : "72/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3940,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.8259811,43.3554497]},
        		"properties" : { 
        				 "NAME" : "St Gabriel", 
        				 "MUNICIPALITY" : "Burlington", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2227 Parkway Dr", 
        				 "POSTALCODE" : "L7P1S9",
        				 "PHONE" : "9053323333",
        				 "FAX" : "9053327566",
        				 "WEB" : "http://schools.hcdsb.org/gabr/default.aspx",
        				 "BOARD_NAME" : "Halton CDSB",
        				 "ProvincalName" : "St Gabriel,Burlington",
        				 "Rating2011_12" : "9", 
        				 "Rating_in_the_most_recent_five_years" : "7.9", 
        				 "Rank2011_12" : "78/2714",
        				 "Rank_in_the_most_recent_five_years" : "228/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3987,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.2424011,43.2037086]},
        		"properties" : { 
        				 "NAME" : "St James", 
        				 "MUNICIPALITY" : "St Catharines", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "615 Geneva St", 
        				 "POSTALCODE" : "L2N2J3",
        				 "PHONE" : "9059343112",
        				 "FAX" : "9059340153",
        				 "WEB" : "http://www.niagaracatholic.ca/niagaraRC/schools/elementary/StJames/2007/",
        				 "BOARD_NAME" : "Niagara CDSB",
        				 "ProvincalName" : "St James,St Catharines",
        				 "Rating2011_12" : "9.4", 
        				 "Rating_in_the_most_recent_five_years" : "9.4", 
        				 "Rank2011_12" : "41/2714",
        				 "Rank_in_the_most_recent_five_years" : "21/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3996,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [0,0]},
        		"properties" : { 
        				 "NAME" : "St James", 
        				 "MUNICIPALITY" : "Tottenham", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "7332 St James Lane", 
        				 "POSTALCODE" : "L0G1W0",
        				 "PHONE" : "9059364191",
        				 "FAX" : "9059369624",
        				 "WEB" : "http://sja.schools.smcdsb.on.ca",
        				 "BOARD_NAME" : "Simcoe Muskoka CDSB",
        				 "ProvincalName" : "St James,Tottenham",
        				 "Rating2011_12" : "9.4", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "41/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4063,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4770889,43.9822655]},
        		"properties" : { 
        				 "NAME" : "St Joseph", 
        				 "MUNICIPALITY" : "Aurora", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2 Glass Dr", 
        				 "POSTALCODE" : "L4G2E8",
        				 "PHONE" : "9057275782",
        				 "FAX" : "9057273702",
        				 "WEB" : "http://sja.ycdsb.ca/",
        				 "BOARD_NAME" : "York CDSB",
        				 "ProvincalName" : "St Joseph,Aurora",
        				 "Rating2011_12" : "9.5", 
        				 "Rating_in_the_most_recent_five_years" : "8.5", 
        				 "Rank2011_12" : "37/2714",
        				 "Rank_in_the_most_recent_five_years" : "86/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4112,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.1643753,44.3342171]},
        		"properties" : { 
        				 "NAME" : "St Joseph's", 
        				 "MUNICIPALITY" : "Gananoque", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "235 Georgiana St", 
        				 "POSTALCODE" : "K7G1M9",
        				 "PHONE" : "6133822361",
        				 "FAX" : "6133822924",
        				 "WEB" : "http://www.cdsbeo.on.ca/School_Home_Pages/St_Joseph-Gananoque.htm",
        				 "BOARD_NAME" : "CDSB of Eastern Ontario",
        				 "ProvincalName" : "St Joseph's,Gananoque",
        				 "Rating2011_12" : "9", 
        				 "Rating_in_the_most_recent_five_years" : "8.1", 
        				 "Rank2011_12" : "78/2714",
        				 "Rank_in_the_most_recent_five_years" : "176/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4113,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.3524246,45.4403343]},
        		"properties" : { 
        				 "NAME" : "St Joseph's", 
        				 "MUNICIPALITY" : "Arnprior", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "324 John St N", 
        				 "POSTALCODE" : "K7S2P6",
        				 "PHONE" : "6136232347",
        				 "FAX" : "6136232659",
        				 "WEB" : "http://sjarnprior.rccdsb.edu.on.ca/",
        				 "BOARD_NAME" : "Renfrew County CDSB",
        				 "ProvincalName" : "St Joseph's,Arnprior",
        				 "Rating2011_12" : "9.1", 
        				 "Rating_in_the_most_recent_five_years" : "9.1", 
        				 "Rank2011_12" : "67/2714",
        				 "Rank_in_the_most_recent_five_years" : "33/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4128,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3435516,43.8674698]},
        		"properties" : { 
        				 "NAME" : "St Justin Martyr", 
        				 "MUNICIPALITY" : "Unionville", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "140 Hollingham Rd", 
        				 "POSTALCODE" : "L3R8K4",
        				 "PHONE" : "9054740284",
        				 "FAX" : "9054741462",
        				 "WEB" : "http://sjn.ycdsb.ca",
        				 "BOARD_NAME" : "York CDSB",
        				 "ProvincalName" : "St Justin Martyr,Unionville",
        				 "Rating2011_12" : "10", 
        				 "Rating_in_the_most_recent_five_years" : "9.9", 
        				 "Rank2011_12" : "1/2714",
        				 "Rank_in_the_most_recent_five_years" : "3/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4154,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.6624832,43.4967918]},
        		"properties" : { 
        				 "NAME" : "St Luke", 
        				 "MUNICIPALITY" : "Oakville", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "2750 Kingsway Dr", 
        				 "POSTALCODE" : "L6J7G5",
        				 "PHONE" : "9058291700",
        				 "FAX" : "9058293369",
        				 "WEB" : "http://schools.hcdsb.org/luke/",
        				 "BOARD_NAME" : "Halton CDSB",
        				 "ProvincalName" : "St Luke,Oakville",
        				 "Rating2011_12" : "9.8", 
        				 "Rating_in_the_most_recent_five_years" : "8.3", 
        				 "Rank2011_12" : "20/2714",
        				 "Rank_in_the_most_recent_five_years" : "127/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4209,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.7388382,43.2356987]},
        		"properties" : { 
        				 "NAME" : "St Martin of Tours", 
        				 "MUNICIPALITY" : "Stoney Creek", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "60 Grays Rd", 
        				 "POSTALCODE" : "L8G2X5",
        				 "PHONE" : "9055232334",
        				 "FAX" : "9056642630",
        				 "WEB" : "http://stmr.hwcdsb.ca/",
        				 "BOARD_NAME" : "Hamilton-Wentworth CDSB",
        				 "ProvincalName" : "St Martin of Tours,Stoney Creek",
        				 "Rating2011_12" : "9.5", 
        				 "Rating_in_the_most_recent_five_years" : "9.4", 
        				 "Rank2011_12" : "37/2714",
        				 "Rank_in_the_most_recent_five_years" : "21/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4270,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3594131,43.7848892]},
        		"properties" : { 
        				 "NAME" : "St Matthias", 
        				 "MUNICIPALITY" : "Toronto", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "101 Van Horne Ave", 
        				 "POSTALCODE" : "M2J2S8",
        				 "PHONE" : "4163935357",
        				 "FAX" : "4163935168",
        				 "WEB" : "http://www.tcdsb.org/schools/stmatthias.asp",
        				 "BOARD_NAME" : "Toronto CDSB",
        				 "ProvincalName" : "St Matthias,Toronto",
        				 "Rating2011_12" : "9.1", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "67/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4329,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.6154175,43.824749]},
        		"properties" : { 
        				 "NAME" : "St Padre Pio", 
        				 "MUNICIPALITY" : "Woodbridge", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "770 NAPA VALLEY AVE", 
        				 "POSTALCODE" : "L4H1W9",
        				 "PHONE" : "9058937082",
        				 "FAX" : "9058938571",
        				 "WEB" : "http://spp.ycdsb.ca/",
        				 "BOARD_NAME" : "York CDSB",
        				 "ProvincalName" : "St Padre Pio,Woodbridge",
        				 "Rating2011_12" : "9.2", 
        				 "Rating_in_the_most_recent_five_years" : "9.5", 
        				 "Rank2011_12" : "57/2714",
        				 "Rank_in_the_most_recent_five_years" : "18/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4320,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [0,0]},
        		"properties" : { 
        				 "NAME" : "Stonebridge", 
        				 "MUNICIPALITY" : "Markham", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "168 Stonebridge Dr", 
        				 "POSTALCODE" : "L6C2Z8",
        				 "PHONE" : "9058872427",
        				 "FAX" : "9058877841",
        				 "WEB" : "http://www.stonebridge.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "Stonebridge,Markham",
        				 "Rating2011_12" : "9.7", 
        				 "Rating_in_the_most_recent_five_years" : "9", 
        				 "Rank2011_12" : "25/2714",
        				 "Rank_in_the_most_recent_five_years" : "40/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4450,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.6019135,43.6360512]},
        		"properties" : { 
        				 "NAME" : "Sts Martha & Mary", 
        				 "MUNICIPALITY" : "Mississauga", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Catholic", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "1760 Bough Beeches Blvd", 
        				 "POSTALCODE" : "L4W2B9",
        				 "PHONE" : "9056249625",
        				 "FAX" : "9056248089",
        				 "WEB" : "http://www.dpcdsb.org/MMARY",
        				 "BOARD_NAME" : "Dufferin-Peel CDSB",
        				 "ProvincalName" : "Sts Martha & Mary,Mississauga",
        				 "Rating2011_12" : "9.6", 
        				 "Rating_in_the_most_recent_five_years" : "8.6", 
        				 "Rank2011_12" : "31/2714",
        				 "Rank_in_the_most_recent_five_years" : "72/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4633,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.4667435,43.8350182]},
        		"properties" : { 
        				 "NAME" : "Thornhill Woods", 
        				 "MUNICIPALITY" : "Thornhill", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "341 Thornhill Woods Dr", 
        				 "POSTALCODE" : "L4J8V6",
        				 "PHONE" : "9053268626",
        				 "FAX" : "9053268057",
        				 "WEB" : "http://www.yrdsb.edu.on.ca/page.cfm?id=S00000099&sc=346",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "Thornhill Woods,Thornhill",
        				 "Rating2011_12" : "9", 
        				 "Rating_in_the_most_recent_five_years" : "8.4", 
        				 "Rank2011_12" : "78/2714",
        				 "Rank_in_the_most_recent_five_years" : "104/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4703,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.0652313,43.9264297]},
        		"properties" : { 
        				 "NAME" : "Valley View", 
        				 "MUNICIPALITY" : "Greenwood", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "3530 Westney Rd", 
        				 "POSTALCODE" : "L0H1H0",
        				 "PHONE" : "9056836208",
        				 "FAX" : "",
        				 "WEB" : "http://valleyview.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "Valley View,Greenwood",
        				 "Rating2011_12" : "9.6", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "31/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4873,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-79.3257904,43.8717613]},
        		"properties" : { 
        				 "NAME" : "William Berczy", 
        				 "MUNICIPALITY" : "Unionville", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "120 Carlton Rd", 
        				 "POSTALCODE" : "L3R1Z9",
        				 "PHONE" : "9054772047",
        				 "FAX" : "9054772373",
        				 "WEB" : "http://www.williamberczy.ps.yrdsb.edu.on.ca/",
        				 "BOARD_NAME" : "York Region DSB",
        				 "ProvincalName" : "William Berczy,Unionville",
        				 "Rating2011_12" : "10", 
        				 "Rating_in_the_most_recent_five_years" : "9.9", 
        				 "Rank2011_12" : "1/2714",
        				 "Rank_in_the_most_recent_five_years" : "3/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 4916,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.5039597,44.2292786]},
        		"properties" : { 
        				 "NAME" : "Winston Churchill", 
        				 "MUNICIPALITY" : "Kingston", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "530 Earl St", 
        				 "POSTALCODE" : "K7L2K3",
        				 "PHONE" : "6135426441",
        				 "FAX" : "6135421132",
        				 "WEB" : "http://winstonchurchill.limestone.on.ca/",
        				 "BOARD_NAME" : "Limestone DSB",
        				 "ProvincalName" : "Winston Churchill,Kingston",
        				 "Rating2011_12" : "9.3", 
        				 "Rating_in_the_most_recent_five_years" : "9.3", 
        				 "Rank2011_12" : "52/2714",
        				 "Rank_in_the_most_recent_five_years" : "24/2268",
        				 "popupContent": "Put more data here" }}
             ]
    };
    