 var schools0 = { 
    "type" : "FeatureCollection",
        "features" : [
             { "type" : "Feature",
        "id" : 573,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.2626419,43.1445503]},
        		"properties" : { 
        				 "NAME" : "Central", 
        				 "MUNICIPALITY" : "Brantford", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "135 George St", 
        				 "POSTALCODE" : "N3W2B2",
        				 "PHONE" : "5197528819",
        				 "FAX" : "",
        				 "WEB" : "http://granderie.ca/centralps/",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Central,Brantford",
        				 "Rating2011_12" : "0", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2706/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 693,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.29978943,42.85289001]},
        		"properties" : { 
        				 "NAME" : "Cochrane", 
        				 "MUNICIPALITY" : "Cochrane", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 999", 
        				 "STREET" : "453A Chalmers Avenue", 
        				 "POSTALCODE" : "P0L1C0",
        				 "PHONE" : "7052723246",
        				 "FAX" : "7052722713",
        				 "WEB" : "www.dsb1.edu.on.ca/schools/cochrane",
        				 "BOARD_NAME" : "DSB Ontario North East",
        				 "ProvincalName" : "Cochrane,Cochrane",
        				 "Rating2011_12" : "0.4", 
        				 "Rating_in_the_most_recent_five_years" : "2.3", 
        				 "Rank2011_12" : "2704/2714",
        				 "Rank_in_the_most_recent_five_years" : "2234/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 708,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.5710602,44.1066513]},
        		"properties" : { 
        				 "NAME" : "College Street", 
        				 "MUNICIPALITY" : "Trenton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "20 South St", 
        				 "POSTALCODE" : "K8V1P8",
        				 "PHONE" : "6133924524",
        				 "FAX" : "6133928607",
        				 "WEB" : "http://www.hpedsb.on.ca/coll/",
        				 "BOARD_NAME" : "Hastings & Prince Edward DSB",
        				 "ProvincalName" : "College Street,Trenton",
        				 "Rating2011_12" : "0", 
        				 "Rating_in_the_most_recent_five_years" : "0.8", 
        				 "Rank2011_12" : "2706/2714",
        				 "Rank_in_the_most_recent_five_years" : "2266/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 945,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.7340164,43.1248093]},
        		"properties" : { 
        				 "NAME" : "Eastdale", 
        				 "MUNICIPALITY" : "Woodstock", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "65 Aileen Dr", 
        				 "POSTALCODE" : "N4S4A2",
        				 "PHONE" : "5195372652",
        				 "FAX" : "5195373695",
        				 "WEB" : "http://www.tvdsb.ca/Eastdale.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Eastdale,Woodstock",
        				 "Rating2011_12" : "0.9", 
        				 "Rating_in_the_most_recent_five_years" : "2.2", 
        				 "Rank2011_12" : "2694/2714",
        				 "Rank_in_the_most_recent_five_years" : "2236/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1613,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.492218,44.2407417]},
        		"properties" : { 
        				 "NAME" : "Frontenac", 
        				 "MUNICIPALITY" : "Kingston", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "38 Cowdy St", 
        				 "POSTALCODE" : "K7K3V9",
        				 "PHONE" : "6135461432",
        				 "FAX" : "6135464454",
        				 "WEB" : "http://frontenacps.limestone.on.ca/",
        				 "BOARD_NAME" : "Limestone DSB",
        				 "ProvincalName" : "Frontenac,Kingston",
        				 "Rating2011_12" : "0.7", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2699/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1677,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-78.8370438,43.8899651]},
        		"properties" : { 
        				 "NAME" : "Gertrude Colpus", 
        				 "MUNICIPALITY" : "Oshawa", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "570 Shakespeare Ave", 
        				 "POSTALCODE" : "L1H3H6",
        				 "PHONE" : "9057258271",
        				 "FAX" : "9057250207",
        				 "WEB" : "http://gertrudecolpus.ddsbschools.ca/",
        				 "BOARD_NAME" : "Durham DSB",
        				 "ProvincalName" : "Gertrude Colpus,Oshawa",
        				 "Rating2011_12" : "0.7", 
        				 "Rating_in_the_most_recent_five_years" : "1.7", 
        				 "Rank2011_12" : "2699/2714",
        				 "Rank_in_the_most_recent_five_years" : "2250/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2015,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [0,0]},
        		"properties" : { 
        				 "NAME" : "Houghton", 
        				 "MUNICIPALITY" : "Langton", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "505 Fairground Side Rd", 
        				 "POSTALCODE" : "N0E1G0",
        				 "PHONE" : "5198752291",
        				 "FAX" : "5198752705",
        				 "WEB" : "http://granderie.ca/houghtonps/home",
        				 "BOARD_NAME" : "Grand Erie DSB",
        				 "ProvincalName" : "Houghton,Langton",
        				 "Rating2011_12" : "0.9", 
        				 "Rating_in_the_most_recent_five_years" : "2.1", 
        				 "Rank2011_12" : "2694/2714",
        				 "Rank_in_the_most_recent_five_years" : "2237/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2193,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.4638672,48.5351028]},
        		"properties" : { 
        				 "NAME" : "Joseph H Kennedy", 
        				 "MUNICIPALITY" : "Matheson", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 640", 
        				 "STREET" : "422 4th Avenue", 
        				 "POSTALCODE" : "P0K1N0",
        				 "PHONE" : "7052732324",
        				 "FAX" : "7052732530",
        				 "WEB" : "http://www.dsb1.edu.on.ca/schools/jhk",
        				 "BOARD_NAME" : "DSB Ontario North East",
        				 "ProvincalName" : "Joseph H Kennedy,Matheson",
        				 "Rating2011_12" : "0", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2706/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 1158,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-75.6703186,45.4400406]},
        		"properties" : { 
        				 "NAME" : "Le Trillium", 
        				 "MUNICIPALITY" : "Vanier", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "French", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "135 rue Alice", 
        				 "POSTALCODE" : "K1L7X5",
        				 "PHONE" : "6137448523",
        				 "FAX" : "6137446759",
        				 "WEB" : "http://www.trillium.cepeo.on.ca",
        				 "BOARD_NAME" : "CƒP de l'Est de l'Ontario",
        				 "ProvincalName" : "Le Trillium,Vanier",
        				 "Rating2011_12" : "0.6", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2702/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2428,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-81.2286987,42.993]},
        		"properties" : { 
        				 "NAME" : "Lorne Avenue", 
        				 "MUNICIPALITY" : "London", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "723 Lorne Ave", 
        				 "POSTALCODE" : "N5W3K7",
        				 "PHONE" : "5194528340",
        				 "FAX" : "5194528349",
        				 "WEB" : "http://www.tvdsb.ca/Lorne.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Lorne Avenue,London",
        				 "Rating2011_12" : "0.8", 
        				 "Rating_in_the_most_recent_five_years" : "2.9", 
        				 "Rank2011_12" : "2697/2714",
        				 "Rank_in_the_most_recent_five_years" : "2189/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2615,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.29978943,42.85289001]},
        		"properties" : { 
        				 "NAME" : "Ministik", 
        				 "MUNICIPALITY" : "Moose Factory", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 160", 
        				 "STREET" : "9 Horden St", 
        				 "POSTALCODE" : "P0L1W0",
        				 "PHONE" : "7056584535",
        				 "FAX" : "7056584024",
        				 "WEB" : "http://edu.hpedsb.on.ca/nhsre/",
        				 "BOARD_NAME" : "Moose Factory Island DSAB",
        				 "ProvincalName" : "Ministik,Moose Factory",
        				 "Rating2011_12" : "0", 
        				 "Rating_in_the_most_recent_five_years" : "0", 
        				 "Rank2011_12" : "2706/2714",
        				 "Rank_in_the_most_recent_five_years" : "2268/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 2659,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.29978943,42.85289001]},
        		"properties" : { 
        				 "NAME" : "Moosonee", 
        				 "MUNICIPALITY" : "Moosonee", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "Box 250", 
        				 "STREET" : "7 First St", 
        				 "POSTALCODE" : "P0L1Y0",
        				 "PHONE" : "7053362365",
        				 "FAX" : "7053363422",
        				 "WEB" : "http://www.opsba.org/index.php?q=who_we_are/member_boards/moosonee_district_school_area_board",
        				 "BOARD_NAME" : "Moosonee DSAB",
        				 "ProvincalName" : "Moosonee,Moosonee",
        				 "Rating2011_12" : "0", 
        				 "Rating_in_the_most_recent_five_years" : "0.5", 
        				 "Rank2011_12" : "2706/2714",
        				 "Rank_in_the_most_recent_five_years" : "2267/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3147,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-77.3964691,44.1646004]},
        		"properties" : { 
        				 "NAME" : "Prince Charles", 
        				 "MUNICIPALITY" : "Belleville", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "75 Ritchie Ave", 
        				 "POSTALCODE" : "K8P3W2",
        				 "PHONE" : "6139620247",
        				 "FAX" : "6139620592",
        				 "WEB" : "http://edu.hpedsb.on.ca/pcb/",
        				 "BOARD_NAME" : "Hastings & Prince Edward DSB",
        				 "ProvincalName" : "Prince Charles,Belleville",
        				 "Rating2011_12" : "0.8", 
        				 "Rating_in_the_most_recent_five_years" : "n/a", 
        				 "Rank2011_12" : "2697/2714",
        				 "Rank_in_the_most_recent_five_years" : "n/a",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3271,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-76.4817123,44.2652283]},
        		"properties" : { 
        				 "NAME" : "Rideau Heights", 
        				 "MUNICIPALITY" : "Kingston", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-8", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "77 MacCauley St", 
        				 "POSTALCODE" : "K7K2V8",
        				 "PHONE" : "6135426155",
        				 "FAX" : "6135420402",
        				 "WEB" : "http://rideauheights.limestone.on.ca/",
        				 "BOARD_NAME" : "Limestone DSB",
        				 "ProvincalName" : "Rideau Heights,Kingston",
        				 "Rating2011_12" : "0.4", 
        				 "Rating_in_the_most_recent_five_years" : "1.4", 
        				 "Rank2011_12" : "2704/2714",
        				 "Rank_in_the_most_recent_five_years" : "2260/2268",
        				 "popupContent": "Put more data here" }},
         { "type" : "Feature",
        "id" : 3626,
            "geometry" : {
                "type" : "Point",
                "coordinates" : [-80.9304886,42.8305244]},
        		"properties" : { 
        				 "NAME" : "Springfield", 
        				 "MUNICIPALITY" : "Springfield", 
    					 "PROVINCE" : "Ontario", 
        				 "TYPE" : "Public", 
       				     "LEVEL" : "Elementary", 
        				 "LANGUAG" : "English", 
        				 "GRADE" : "JK-6", 
        				 "SUITE" : "", 
        				 "POBOX" : "", 
        				 "STREET" : "51336 Ron McNeil Line", 
        				 "POSTALCODE" : "N0L2J0",
        				 "PHONE" : "5197654162",
        				 "FAX" : "5197654247",
        				 "WEB" : "http://www.tvdsb.ca/Springfield.cfm",
        				 "BOARD_NAME" : "Thames Valley DSB",
        				 "ProvincalName" : "Springfield,Springfield",
        				 "Rating2011_12" : "1", 
        				 "Rating_in_the_most_recent_five_years" : "2.4", 
        				 "Rank2011_12" : "2691/2714",
        				 "Rank_in_the_most_recent_five_years" : "2230/2268",
        				 "popupContent": "Put more data here" }}
             ]
    };
    